set loc en

# Window title
::msgcat::mcset $loc Character

::msgcat::mcset $loc TestChar W

# Menu
::msgcat::mcset $loc "Change Icon"
::msgcat::mcset $loc "Change Name"
::msgcat::mcset $loc "File Character"

# Pages
::msgcat::mcset $loc Info
::msgcat::mcset $loc Flags
::msgcat::mcset $loc Mutations
::msgcat::mcset $loc Virtues
::msgcat::mcset $loc Notes

::msgcat::mcset $loc "Name"
::msgcat::mcset $loc "Sex"
::msgcat::mcset $loc "Race"
::msgcat::mcset $loc "Class"
::msgcat::mcset $loc "Title"
::msgcat::mcset $loc "HP" 
::msgcat::mcset $loc "SP"
::msgcat::mcset $loc "Realm 1" 
::msgcat::mcset $loc "Realm 2"
::msgcat::mcset $loc "Patron"
::msgcat::mcset $loc Age
::msgcat::mcset $loc Height
::msgcat::mcset $loc Weight
::msgcat::mcset $loc Status
::msgcat::mcset $loc Maximize
::msgcat::mcset $loc Preserve
::msgcat::mcset $loc Self
::msgcat::mcset $loc RB
::msgcat::mcset $loc CB
::msgcat::mcset $loc EB
::msgcat::mcset $loc Best
::msgcat::mcset $loc STR:
::msgcat::mcset $loc INT:
::msgcat::mcset $loc WIS:
::msgcat::mcset $loc DEX:
::msgcat::mcset $loc CON:
::msgcat::mcset $loc CHR:
::msgcat::mcset $loc Level
::msgcat::mcset $loc "Cur Exp"
::msgcat::mcset $loc "Max Exp"
::msgcat::mcset $loc "Adv Exp"
::msgcat::mcset $loc Gold
::msgcat::mcset $loc Burden
::msgcat::mcset $loc "Armor"
::msgcat::mcset $loc "Fight"
::msgcat::mcset $loc "Melee"
::msgcat::mcset $loc "Shoot"
::msgcat::mcset $loc "Blows"
::msgcat::mcset $loc "Shots"
::msgcat::mcset $loc "Infra"
::msgcat::mcset $loc "+ to Skill"
::msgcat::mcset $loc "Deadliness"
::msgcat::mcset $loc "Blows/Round"
::msgcat::mcset $loc "Shots/Round"
::msgcat::mcset $loc "Saving Throw"
::msgcat::mcset $loc "Stealth"
::msgcat::mcset $loc "Fighting"
::msgcat::mcset $loc "Shooting"
::msgcat::mcset $loc "Disarming"
::msgcat::mcset $loc "Magic Device"
::msgcat::mcset $loc "Perception"
::msgcat::mcset $loc "Searching"
::msgcat::mcset $loc Infravision
::msgcat::mcset $loc "Awful"
::msgcat::mcset $loc "Very Bad"
::msgcat::mcset $loc "Bad"
::msgcat::mcset $loc "Poor"
::msgcat::mcset $loc "Mediocre"
::msgcat::mcset $loc "Fair"
::msgcat::mcset $loc "Good"
::msgcat::mcset $loc "Very Good"
::msgcat::mcset $loc "Excellent"
::msgcat::mcset $loc "Superb"
::msgcat::mcset $loc "Heroic"
::msgcat::mcset $loc "Legendary"
::msgcat::mcset $loc "Excellent"
::msgcat::mcset $loc "Chaos Rank"
::msgcat::mcset $loc "Amber \[%d\]"
