set loc en

# Window title
::msgcat::mcset $loc Equipment
::msgcat::mcset $loc Inventory
::msgcat::mcset $loc Floor
::msgcat::mcset $loc Items

# Window
::msgcat::mcset $loc Inscription:
::msgcat::mcset $loc Displayed
::msgcat::mcset $loc Total
::msgcat::mcset $loc Threshold
::msgcat::mcset $loc Limit
::msgcat::mcset $loc "%d item"
::msgcat::mcset $loc "%d items"

# Usage
::msgcat::mcset $loc Activate
::msgcat::mcset $loc Remove
::msgcat::mcset $loc Browse
::msgcat::mcset $loc Fire
::msgcat::mcset $loc Refuel
::msgcat::mcset $loc Eat
::msgcat::mcset $loc Drink
::msgcat::mcset $loc Read
::msgcat::mcset $loc Jam
::msgcat::mcset $loc Use
::msgcat::mcset $loc Zap
::msgcat::mcset $loc Aim
::msgcat::mcset $loc Wield

# Popup
::msgcat::mcset $loc *Destroy*
::msgcat::mcset $loc Sell
::msgcat::mcset $loc Drop
::msgcat::mcset $loc "Select This Item"
::msgcat::mcset $loc Inspect
::msgcat::mcset $loc Inscribe
::msgcat::mcset $loc Uninscribe

# Options
::msgcat::mcset $loc "Show Flavors"
::msgcat::mcset $loc "Show Icons"
::msgcat::mcset $loc "Show Labels"
::msgcat::mcset $loc "Show Weights"
::msgcat::mcset $loc "Use Metric"
::msgcat::mcset $loc "Always On Top"
::msgcat::mcset $loc "Graphics Mode"
::msgcat::mcset $loc "List Mode"

