/*
 * FILE : commands_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
#ifdef __cplusplus
}
#endif

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}



/*****************************************************************************
 * $Header$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    initcommands

#define SWIG_name    "commands"


#include "angband.h"

extern void do_cmd_view_map();
extern void do_cmd_go_up();
extern void do_cmd_go_down();
extern void do_cmd_search();
extern void do_cmd_toggle_search();
extern void do_cmd_open();
extern void do_cmd_close();
extern void do_cmd_tunnel();
extern void do_cmd_disarm();
extern void do_cmd_alter();
extern void do_cmd_spike();
extern void do_cmd_walk(int );
extern void do_cmd_stay(int );
extern void do_cmd_run();
extern void do_cmd_rest();
extern void do_cmd_fire();
extern void do_cmd_throw();
extern void do_cmd_throw_aux(int );
extern void do_cmd_inven();
extern void do_cmd_equip();
extern void do_cmd_wield();
extern void do_cmd_takeoff();
extern void do_cmd_drop();
extern void do_cmd_destroy();
extern void do_cmd_observe();
extern void do_cmd_uninscribe();
extern void do_cmd_inscribe();
extern void do_cmd_refill();
extern void do_cmd_target();
extern void do_cmd_look();
extern void do_cmd_locate();
extern void do_cmd_query_symbol();
extern void do_cmd_redraw();
extern void do_cmd_message_one();
extern void do_cmd_messages();
extern void do_cmd_options(byte );
extern void do_cmd_pref();
extern void do_cmd_macros();
extern void do_cmd_visuals();
extern void do_cmd_colors();
extern void do_cmd_note();
extern void do_cmd_version();
extern void do_cmd_feeling();
extern void do_cmd_load_screen();
extern void do_cmd_save_screen();
extern void do_cmd_knowledge();
extern void do_cmd_checkquest();
extern void do_cmd_time();
extern void do_cmd_browse();
extern void do_cmd_study();
extern void do_cmd_cast();
extern void do_cmd_pray();
extern void do_cmd_pet();
extern void do_cmd_eat_food();
extern void do_cmd_quaff_potion();
extern void do_cmd_read_scroll();
extern void do_cmd_aim_wand();
extern void do_cmd_use_staff();
extern void do_cmd_zap_rod();
extern void do_cmd_activate();
extern void do_cmd_rerate();
extern void do_cmd_help();
extern void do_cmd_suicide();
extern void do_cmd_save_game(int );
extern void do_cmd_save_and_exit();
extern void do_cmd_racial_power();
extern void do_cmd_store(field_type *);
extern void do_cmd_mindcraft();
extern void do_cmd_knowledge_mutations();
extern bool do_cmd_disarm_aux(cave_type *,int );
static PyObject *_wrap_do_cmd_view_map(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_view_map")) 
        return NULL;
    do_cmd_view_map();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_go_up(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_go_up")) 
        return NULL;
    do_cmd_go_up();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_go_down(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_go_down")) 
        return NULL;
    do_cmd_go_down();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_search(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_search")) 
        return NULL;
    do_cmd_search();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_toggle_search(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_toggle_search")) 
        return NULL;
    do_cmd_toggle_search();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_open(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_open")) 
        return NULL;
    do_cmd_open();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_close(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_close")) 
        return NULL;
    do_cmd_close();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_tunnel(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_tunnel")) 
        return NULL;
    do_cmd_tunnel();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_disarm(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_disarm")) 
        return NULL;
    do_cmd_disarm();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_alter(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_alter")) 
        return NULL;
    do_cmd_alter();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_spike(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_spike")) 
        return NULL;
    do_cmd_spike();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_walk(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:do_cmd_walk",&_arg0)) 
        return NULL;
    do_cmd_walk(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_stay(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:do_cmd_stay",&_arg0)) 
        return NULL;
    do_cmd_stay(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_run(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_run")) 
        return NULL;
    do_cmd_run();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_rest(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_rest")) 
        return NULL;
    do_cmd_rest();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_fire(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_fire")) 
        return NULL;
    do_cmd_fire();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_throw(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_throw")) 
        return NULL;
    do_cmd_throw();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_throw_aux(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:do_cmd_throw_aux",&_arg0)) 
        return NULL;
    do_cmd_throw_aux(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_inven(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_inven")) 
        return NULL;
    do_cmd_inven();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_equip(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_equip")) 
        return NULL;
    do_cmd_equip();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_wield(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_wield")) 
        return NULL;
    do_cmd_wield();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_takeoff(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_takeoff")) 
        return NULL;
    do_cmd_takeoff();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_drop(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_drop")) 
        return NULL;
    do_cmd_drop();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_destroy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_destroy")) 
        return NULL;
    do_cmd_destroy();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_observe(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_observe")) 
        return NULL;
    do_cmd_observe();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_uninscribe(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_uninscribe")) 
        return NULL;
    do_cmd_uninscribe();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_inscribe(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_inscribe")) 
        return NULL;
    do_cmd_inscribe();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_refill(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_refill")) 
        return NULL;
    do_cmd_refill();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_target(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_target")) 
        return NULL;
    do_cmd_target();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_look(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_look")) 
        return NULL;
    do_cmd_look();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_locate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_locate")) 
        return NULL;
    do_cmd_locate();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_query_symbol(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_query_symbol")) 
        return NULL;
    do_cmd_query_symbol();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_redraw(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_redraw")) 
        return NULL;
    do_cmd_redraw();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_message_one(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_message_one")) 
        return NULL;
    do_cmd_message_one();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_messages(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_messages")) 
        return NULL;
    do_cmd_messages();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_options(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"b:do_cmd_options",&_arg0)) 
        return NULL;
    do_cmd_options(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_pref(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_pref")) 
        return NULL;
    do_cmd_pref();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_macros(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_macros")) 
        return NULL;
    do_cmd_macros();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_visuals(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_visuals")) 
        return NULL;
    do_cmd_visuals();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_colors(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_colors")) 
        return NULL;
    do_cmd_colors();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_note(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_note")) 
        return NULL;
    do_cmd_note();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_version(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_version")) 
        return NULL;
    do_cmd_version();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_feeling(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_feeling")) 
        return NULL;
    do_cmd_feeling();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_load_screen(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_load_screen")) 
        return NULL;
    do_cmd_load_screen();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_save_screen(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_save_screen")) 
        return NULL;
    do_cmd_save_screen();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_knowledge(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_knowledge")) 
        return NULL;
    do_cmd_knowledge();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_checkquest(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_checkquest")) 
        return NULL;
    do_cmd_checkquest();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_time(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_time")) 
        return NULL;
    do_cmd_time();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_browse(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_browse")) 
        return NULL;
    do_cmd_browse();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_study(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_study")) 
        return NULL;
    do_cmd_study();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_cast(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_cast")) 
        return NULL;
    do_cmd_cast();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_pray(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_pray")) 
        return NULL;
    do_cmd_pray();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_pet(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_pet")) 
        return NULL;
    do_cmd_pet();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_eat_food(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_eat_food")) 
        return NULL;
    do_cmd_eat_food();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_quaff_potion(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_quaff_potion")) 
        return NULL;
    do_cmd_quaff_potion();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_read_scroll(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_read_scroll")) 
        return NULL;
    do_cmd_read_scroll();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_aim_wand(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_aim_wand")) 
        return NULL;
    do_cmd_aim_wand();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_use_staff(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_use_staff")) 
        return NULL;
    do_cmd_use_staff();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_zap_rod(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_zap_rod")) 
        return NULL;
    do_cmd_zap_rod();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_activate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_activate")) 
        return NULL;
    do_cmd_activate();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_rerate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_rerate")) 
        return NULL;
    do_cmd_rerate();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_help(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_help")) 
        return NULL;
    do_cmd_help();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_suicide(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_suicide")) 
        return NULL;
    do_cmd_suicide();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_save_game(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:do_cmd_save_game",&_arg0)) 
        return NULL;
    do_cmd_save_game(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_save_and_exit(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_save_and_exit")) 
        return NULL;
    do_cmd_save_and_exit();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_racial_power(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_racial_power")) 
        return NULL;
    do_cmd_racial_power();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_store(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    field_type * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:do_cmd_store",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_field_type_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of do_cmd_store. Expected _field_type_p.");
        return NULL;
        }
    }
    do_cmd_store(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_mindcraft(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_mindcraft")) 
        return NULL;
    do_cmd_mindcraft();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_knowledge_mutations(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":do_cmd_knowledge_mutations")) 
        return NULL;
    do_cmd_knowledge_mutations();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_do_cmd_disarm_aux(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    cave_type * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:do_cmd_disarm_aux",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_cave_type_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of do_cmd_disarm_aux. Expected _cave_type_p.");
        return NULL;
        }
    }
    _result = (bool )do_cmd_disarm_aux(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyMethodDef commandsMethods[] = {
	 { "do_cmd_disarm_aux", _wrap_do_cmd_disarm_aux, 1 },
	 { "do_cmd_knowledge_mutations", _wrap_do_cmd_knowledge_mutations, 1 },
	 { "do_cmd_mindcraft", _wrap_do_cmd_mindcraft, 1 },
	 { "do_cmd_store", _wrap_do_cmd_store, 1 },
	 { "do_cmd_racial_power", _wrap_do_cmd_racial_power, 1 },
	 { "do_cmd_save_and_exit", _wrap_do_cmd_save_and_exit, 1 },
	 { "do_cmd_save_game", _wrap_do_cmd_save_game, 1 },
	 { "do_cmd_suicide", _wrap_do_cmd_suicide, 1 },
	 { "do_cmd_help", _wrap_do_cmd_help, 1 },
	 { "do_cmd_rerate", _wrap_do_cmd_rerate, 1 },
	 { "do_cmd_activate", _wrap_do_cmd_activate, 1 },
	 { "do_cmd_zap_rod", _wrap_do_cmd_zap_rod, 1 },
	 { "do_cmd_use_staff", _wrap_do_cmd_use_staff, 1 },
	 { "do_cmd_aim_wand", _wrap_do_cmd_aim_wand, 1 },
	 { "do_cmd_read_scroll", _wrap_do_cmd_read_scroll, 1 },
	 { "do_cmd_quaff_potion", _wrap_do_cmd_quaff_potion, 1 },
	 { "do_cmd_eat_food", _wrap_do_cmd_eat_food, 1 },
	 { "do_cmd_pet", _wrap_do_cmd_pet, 1 },
	 { "do_cmd_pray", _wrap_do_cmd_pray, 1 },
	 { "do_cmd_cast", _wrap_do_cmd_cast, 1 },
	 { "do_cmd_study", _wrap_do_cmd_study, 1 },
	 { "do_cmd_browse", _wrap_do_cmd_browse, 1 },
	 { "do_cmd_time", _wrap_do_cmd_time, 1 },
	 { "do_cmd_checkquest", _wrap_do_cmd_checkquest, 1 },
	 { "do_cmd_knowledge", _wrap_do_cmd_knowledge, 1 },
	 { "do_cmd_save_screen", _wrap_do_cmd_save_screen, 1 },
	 { "do_cmd_load_screen", _wrap_do_cmd_load_screen, 1 },
	 { "do_cmd_feeling", _wrap_do_cmd_feeling, 1 },
	 { "do_cmd_version", _wrap_do_cmd_version, 1 },
	 { "do_cmd_note", _wrap_do_cmd_note, 1 },
	 { "do_cmd_colors", _wrap_do_cmd_colors, 1 },
	 { "do_cmd_visuals", _wrap_do_cmd_visuals, 1 },
	 { "do_cmd_macros", _wrap_do_cmd_macros, 1 },
	 { "do_cmd_pref", _wrap_do_cmd_pref, 1 },
	 { "do_cmd_options", _wrap_do_cmd_options, 1 },
	 { "do_cmd_messages", _wrap_do_cmd_messages, 1 },
	 { "do_cmd_message_one", _wrap_do_cmd_message_one, 1 },
	 { "do_cmd_redraw", _wrap_do_cmd_redraw, 1 },
	 { "do_cmd_query_symbol", _wrap_do_cmd_query_symbol, 1 },
	 { "do_cmd_locate", _wrap_do_cmd_locate, 1 },
	 { "do_cmd_look", _wrap_do_cmd_look, 1 },
	 { "do_cmd_target", _wrap_do_cmd_target, 1 },
	 { "do_cmd_refill", _wrap_do_cmd_refill, 1 },
	 { "do_cmd_inscribe", _wrap_do_cmd_inscribe, 1 },
	 { "do_cmd_uninscribe", _wrap_do_cmd_uninscribe, 1 },
	 { "do_cmd_observe", _wrap_do_cmd_observe, 1 },
	 { "do_cmd_destroy", _wrap_do_cmd_destroy, 1 },
	 { "do_cmd_drop", _wrap_do_cmd_drop, 1 },
	 { "do_cmd_takeoff", _wrap_do_cmd_takeoff, 1 },
	 { "do_cmd_wield", _wrap_do_cmd_wield, 1 },
	 { "do_cmd_equip", _wrap_do_cmd_equip, 1 },
	 { "do_cmd_inven", _wrap_do_cmd_inven, 1 },
	 { "do_cmd_throw_aux", _wrap_do_cmd_throw_aux, 1 },
	 { "do_cmd_throw", _wrap_do_cmd_throw, 1 },
	 { "do_cmd_fire", _wrap_do_cmd_fire, 1 },
	 { "do_cmd_rest", _wrap_do_cmd_rest, 1 },
	 { "do_cmd_run", _wrap_do_cmd_run, 1 },
	 { "do_cmd_stay", _wrap_do_cmd_stay, 1 },
	 { "do_cmd_walk", _wrap_do_cmd_walk, 1 },
	 { "do_cmd_spike", _wrap_do_cmd_spike, 1 },
	 { "do_cmd_alter", _wrap_do_cmd_alter, 1 },
	 { "do_cmd_disarm", _wrap_do_cmd_disarm, 1 },
	 { "do_cmd_tunnel", _wrap_do_cmd_tunnel, 1 },
	 { "do_cmd_close", _wrap_do_cmd_close, 1 },
	 { "do_cmd_open", _wrap_do_cmd_open, 1 },
	 { "do_cmd_toggle_search", _wrap_do_cmd_toggle_search, 1 },
	 { "do_cmd_search", _wrap_do_cmd_search, 1 },
	 { "do_cmd_go_down", _wrap_do_cmd_go_down, 1 },
	 { "do_cmd_go_up", _wrap_do_cmd_go_up, 1 },
	 { "do_cmd_view_map", _wrap_do_cmd_view_map, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void,initcommands)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("commands", commandsMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"OPT_FLAG_BIRTH", PyInt_FromLong((long) 0x01));
	 PyDict_SetItemString(d,"OPT_FLAG_SERVER", PyInt_FromLong((long) 0x02));
	 PyDict_SetItemString(d,"OPT_FLAG_PLAYER", PyInt_FromLong((long) 0x04));
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_byte","_unsigned_char",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_cptr","_char_p",0);
	 SWIG_RegisterMapping("_char_p","_cptr",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_s32b",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_s16b","_signed_short",0);
	 SWIG_RegisterMapping("_s16b","_short",0);
	 SWIG_RegisterMapping("_unsigned_short","_u16b",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_s32b","_signed_int",0);
	 SWIG_RegisterMapping("_s32b","_int",0);
	 SWIG_RegisterMapping("_signed_short","_s16b",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_char","_byte",0);
	 SWIG_RegisterMapping("_unsigned_int","_u32b",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_u16b",0);
	 SWIG_RegisterMapping("_short","_s16b",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_u32b",0);
	 SWIG_RegisterMapping("_int","_s32b",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 SWIG_RegisterMapping("_u16b","_unsigned_short",0);
	 SWIG_RegisterMapping("_u16b","_short",0);
	 SWIG_RegisterMapping("_u32b","_unsigned_int",0);
	 SWIG_RegisterMapping("_u32b","_int",0);
}
