/*
 * FILE : .\src\event_wrap.c
 * 
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20000417-1444 (Alpha 2)
 * 
 * Portions Copyright (c) 1995-1999
 * The University of Utah, The Regents of the University of California, and
 * The University of Chicago.  Permission is granted to use and distribute this
 * file in any manner provided this notice remains intact.
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGSTATICRUNTIME(a) static a
#endif

/* Type information structure */

typedef struct _swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  struct _swig_type_info  *next;
  struct _swig_type_info  *prev;
} _swig_type_info;

/* Constant information structure */
typedef struct _swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    _swig_type_info **ptype;
} _swig_const_info;

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(_swig_type_info *) SWIG_TypeRegister(_swig_type_info *);
SWIGEXPORT(_swig_type_info *) SWIG_TypeCheck(char *, _swig_type_info *);
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, _swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, _swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, _swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, _swig_const_info constants[]);

/* External declarations when using runtime libraries */

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

static _swig_type_info *swig_types = 0;

/* Register type mappings with the type-checker */
SWIGSTATICRUNTIME(_swig_type_info *)
SWIG_TypeRegister(_swig_type_info *ti) {
  _swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_types;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_types;
  swig_types = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGSTATICRUNTIME(_swig_type_info *) 
SWIG_TypeCheck(char *c, _swig_type_info *ty) {
  _swig_type_info *s;
  char *sn;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element is always just the name */
  while (s) {
    sn = s->name;
    if ((c == sn) || ((*c == *sn) && (strcmp(sn,c) == 0))) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Convert a pointer value */
SWIGSTATICRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, _swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  _swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    if ((!obj) || !(PyCObject_Check(obj))) goto type_error;
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    if ((!obj) || !(PyString_Check(obj))) goto type_error;
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return 0;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    if (tc->converter) {
      *ptr = (*tc->converter)((void *) p);
    }
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, _swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGSTATICRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, _swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGSTATICRUNTIME(void)
SWIG_InstallConstants(PyObject *d, _swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif


/* ---- TYPES TABLE (BEGIN) ---- */
#define  SWIGTYPE_object_type_p _swig_types[0] 
#define  SWIGTYPE_int_p _swig_types[1] 
#define  SWIGTYPE_cptr_p _swig_types[2] 
#define  SWIGTYPE_PyObject_p _swig_types[3] 
#define  SWIGTYPE_byte_p _swig_types[4] 
static _swig_type_info *_swig_types[6];
/* ---- TYPES TABLE (END) ---- */

#define SWIG_init    initeventc

#define SWIG_name    "eventc"


#include "event.h"

/* Array of the Python objects */
static PyObject *python_callbacks[MAX_EVENT];


void eat_callback(int sval)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[CMD_EAT_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", sval);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* Void */
	return;
}


void kill_monster_callback(int r_idx)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[KILL_MONSTER_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", r_idx);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* Void */
	return;
}


bool building_command_callback(int number, int action)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[BUILDING_COMMAND_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", number, action);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool player_move_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[PLAYER_MOVE_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool cmd_open_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[CMD_OPEN_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool cmd_search_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[CMD_SEARCH_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool player_search_grid_callback(y, x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[PLAYER_SEARCH_GRID_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool cmd_feeling_callback(int feeling)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[CMD_FEELING_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", feeling);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool use_skill_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[USE_SKILL_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool cmd_go_up_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[CMD_GO_UP_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


long get_world_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	long res = 0;

	/* Get the Python object */
	func = python_callbacks[GET_WORLD_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


long get_player_class_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	long res = 0;

	/* Get the Python object */
	func = python_callbacks[GET_PLAYER_CLASS_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


long get_player_realms_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	long res = 0;

	/* Get the Python object */
	func = python_callbacks[GET_PLAYER_REALMS_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


long get_player_race_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	long res = 0;

	/* Get the Python object */
	func = python_callbacks[GET_PLAYER_RACE_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}

cptr get_script_window_line(int line)
{
	PyObject *func, *arglist;
	PyObject *result;
	cptr res = "";

	/* Get the Python object */
	func = python_callbacks[GET_SCRIPT_WINDOW_LINE_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", line);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		if (result && PyString_Check(result))
		{
			res = string_make(PyString_AsString(result));
		}

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


void new_game_callback(void)
{
	PyObject *func;
	PyObject *result;
	PyObject *arglist;

	/* Get the Python object */
	func = python_callbacks[NEW_GAME_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");
		
		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the argument */
		Py_XDECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}
}


void play_game_callback(void)
{
	PyObject *func;
	PyObject *result;
	PyObject *arglist;

	/* Get the Python object */
	func = python_callbacks[PLAY_GAME_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");
		
		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the argument */
		Py_XDECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}
}


cptr save_game_callback(void)
{
	PyObject *func;
	PyObject *result;
	cptr res = NULL;

	/* Get the Python object */
	func = python_callbacks[SAVE_GAME_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, NULL);

		if (result && PyString_Check(result))
		{
			res = string_make(PyString_AsString(result));
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


void load_game_callback(char *data)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[LOAD_GAME_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(s)", data);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* Void */
	return;
}


void leave_level_callback(int level)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[LEAVE_LEVEL_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", level);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* Void */
	return;
}


void enter_level_callback(int level)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[ENTER_LEVEL_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", level);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* Void */
	return;
}


bool player_enter_grid_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[PLAYER_ENTER_GRID_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool generate_level_callback(int level)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[GENERATE_LEVEL_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", level);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool generate_wilderness_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[GENERATE_WILDERNESS_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool enter_wilderness_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[ENTER_WILDERNESS_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool leave_wilderness_callback(int y, int x)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[LEAVE_WILDERNESS_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", y, x);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


void store_examine_callback(object_type *o_ptr)
{
	PyObject *func, *arglist;
	PyObject *result;
	char _ptemp[128];

	/* Get the Python object */
	func = python_callbacks[STORE_EXAMINE_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		SWIG_MakePtr(_ptemp, o_ptr, SWIGTYPE_object_type_p);
		arglist = Py_BuildValue("(s)", _ptemp);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* Void */
	return;
}


bool monster_move_callback(int *mm, int m_idx)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;
	int i;

	/* Get the Python object */
	func = python_callbacks[MONSTER_MOVE_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", m_idx);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyList_Check(result))
		{
			for (i = 0; i < PyList_Size(result); i++)
			{
				mm[i] = PyInt_AsLong(PyList_GetItem(result,i));
			}

			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


void create_monster_callback(int m_idx)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[CREATE_MONSTER_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", m_idx);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* void */
	return;
}


void delete_monster_callback(int m_idx)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[DELETE_MONSTER_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", m_idx);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* void */
	return;
}


void copy_monster_callback(int i1, int i2)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[COPY_MONSTER_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((ii))", i1, i2);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* Free the result */
		Py_XDECREF(result);
	}

	/* void */
	return;
}


char inkey_borg_callback(bool inkey_base, bool inkey_xtra,
                         bool inkey_flag, bool inkey_scan)
{
	PyObject *func, *arglist;
	PyObject *result;
	char res = 0;

	/* Get the Python object */
	func = python_callbacks[INKEY_BORG_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("((iiii))", inkey_base, inkey_xtra,
		                                  inkey_flag, inkey_scan);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = (char)PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


char inkey_callback(char key)
{
	PyObject *func, *arglist;
	PyObject *result;
	char res = 0;

	/* Get the Python object */
	func = python_callbacks[INKEY_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(i)", key);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = (char)PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool get_player_flags_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[GET_PLAYER_FLAGS_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


long sense_inventory_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	long res = 0;

	/* Get the Python object */
	func = python_callbacks[SENSE_INVENTORY_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool destroy_object_callback(object_type *o_ptr, int number)
{
	PyObject *func, *arglist;
	PyObject *result;
	char _ptemp[128];
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[DESTROY_OBJECT_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		SWIG_MakePtr(_ptemp, o_ptr, SWIGTYPE_object_type_p);
		arglist = Py_BuildValue("((si))", _ptemp, number);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


PyObject* object_create_callback(object_type *o_ptr)
{
	PyObject *func, *arglist;
	PyObject *result = NULL;
	char _ptemp[128];

	/* Get the Python object */
	func = python_callbacks[OBJECT_CREATE_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		SWIG_MakePtr(_ptemp, o_ptr, SWIGTYPE_object_type_p);
		arglist = Py_BuildValue("(s)", _ptemp);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* We don't free the result, since we store it! */
	}

	/* Return the object */
	return result;
}


PyObject* object_load_callback(char *code)
{
	PyObject *func, *arglist;
	PyObject *result;

	/* Get the Python object */
	func = python_callbacks[OBJECT_LOAD_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(s)", code);

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		/* We don't free the result, since we store it! */
	}

	/* Return the object */
	return result;
}


/* Object callbacks */
bool object_eat_callback(object_type *o_ptr)
{
	PyObject *result;
	bool res = FALSE;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "object_eat_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "object_eat_hook", "");

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool object_browse_callback(object_type *o_ptr)
{
	PyObject *result;
	bool res = FALSE;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "object_browse_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "object_browse_hook", "");

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool object_cast_callback(object_type *o_ptr)
{
	PyObject *result;
	bool res = FALSE;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "object_cast_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "object_cast_hook", "");

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


cptr object_save_callback(object_type *o_ptr)
{
	PyObject *result;
	cptr res = NULL;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "object_save_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "object_save_hook", "");

		if (result && PyString_Check(result))
		{
			res = string_make(PyString_AsString(result));
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


void object_delete_callback(object_type *o_ptr)
{
	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "object_delete_hook"))
	{
		PyObject *result;

		result = PyObject_CallMethod(o_ptr->python, "object_delete_hook", "");

		/* Free the result */
		Py_XDECREF(result);

		/* Free the Python object */
		Py_XDECREF(o_ptr->python);
	}
}


PyObject* object_copy_callback(object_type *o_ptr, object_type *j_ptr)
{
	PyObject *result = NULL;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "object_copy_hook"))
	{
		char _ptemp[128];

		/* Build the argument-list */
		SWIG_MakePtr(_ptemp, j_ptr, SWIGTYPE_object_type_p);

		result = PyObject_CallMethod(o_ptr->python, "object_copy_hook", "(s)", _ptemp);

		/* We don't free the result, since we store it! */
	}

	/* Return the object */
	return result;
}


long get_object_level_callback(object_type *o_ptr)
{
	PyObject *result;
	long res = 0;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_level_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_level_hook", "");

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


long get_object_cost_callback(object_type *o_ptr)
{
	PyObject *result;
	long res = 0;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_cost_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_cost_hook", "");

		if (result && PyInt_Check(result))
		{
			res = PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


cptr get_object_name_callback(object_type *o_ptr)
{
	PyObject *result;
	cptr res = "test";

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_name_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_name_hook", "");

		if (result && PyString_Check(result))
		{
			res = PyString_AsString(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


byte get_object_d_attr_callback(object_type *o_ptr)
{
	PyObject *result;
	byte res = 0;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_d_attr_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_d_attr_hook", "");

		if (result && PyInt_Check(result))
		{
			res = (byte)PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


byte get_object_x_attr_callback(object_type *o_ptr)
{
	PyObject *result;
	byte res = 0;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_x_attr_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_x_attr_hook", "");

		if (result && PyInt_Check(result))
		{
			res = (byte)PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


char get_object_d_char_callback(object_type *o_ptr)
{
	PyObject *result;
	char res = '\0';

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_d_char_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_d_char_hook", "");

		if (result && PyInt_Check(result))
		{
			res = (char)PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


char get_object_x_char_callback(object_type *o_ptr)
{
	PyObject *result;
	char res = '\0';

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_x_char_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_x_char_hook", "");

		if (result && PyInt_Check(result))
		{
			res = (char)PyInt_AsLong(result);
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool get_object_aware_callback(object_type *o_ptr)
{
	PyObject *result;
	bool res = FALSE;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_aware_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_aware_hook", "");

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool get_object_tried_callback(object_type *o_ptr)
{
	PyObject *result;
	bool res = FALSE;

	if (o_ptr && o_ptr->python &&
	    PyObject_HasAttrString(o_ptr->python, "get_object_tried_hook"))
	{
		result = PyObject_CallMethod(o_ptr->python, "get_object_tried_hook", "");

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool player_outfit_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[PLAYER_OUTFIT_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result))
		{
			if (PyInt_AsLong(result))
				res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool wilderness_init_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[WILDERNESS_INIT_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool free_object_kind_list_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[FREE_OBJECT_KIND_LIST_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}


bool init_object_kind_list_callback(void)
{
	PyObject *func, *arglist;
	PyObject *result;
	bool res = FALSE;

	/* Get the Python object */
	func = python_callbacks[INIT_OBJECT_KIND_LIST_EVENT];

	/* Callback installed */
	if (func)
	{
		/* Build the argument-list */
		arglist = Py_BuildValue("(())");

		/* Call the object with the correct arguments */
		result = PyEval_CallObject(func, arglist);

		/* Free the arguments */
		Py_DECREF(arglist);

		if (result && PyInt_Check(result) && PyInt_AsLong(result))
		{
			res = TRUE;
		}

		/* Free the result */
		Py_XDECREF(result);
	}

	return res;
}



void set_callback(int event, PyObject *PyFunc)
{
	/* Dispose of previous callback */
	Py_XDECREF(python_callbacks[event]);

	/* Add a reference to new callback */
	Py_XINCREF(PyFunc);

	/* Remember new callback */
	python_callbacks[event] = PyFunc;
}

PyObject *get_callback(int event)
{
	/* Add a reference to new callback */
	Py_XINCREF(python_callbacks[event]);

	/* Remember new callback */
	return python_callbacks[event];
}

void remove_callback(int event)
{
	/* Dispose old callback */
	Py_XDECREF(python_callbacks[event]);

	python_callbacks[event] = NULL;
}

extern void new_game_callback();
extern void load_game_callback(char *);
extern cptr save_game_callback();
extern void play_game_callback();
extern void eat_callback(int );
extern void kill_monster_callback(int );
extern bool player_move_callback(int ,int );
extern bool cmd_open_callback(int ,int );
extern bool cmd_search_callback(int ,int );
extern bool cmd_feeling_callback(int );
extern bool cmd_go_up_callback();
extern bool building_command_callback(int ,int );
extern bool player_enter_grid_callback(int ,int );
extern bool player_search_grid_callback(int ,int );
extern bool generate_level_callback(int );
extern void leave_level_callback(int );
extern void enter_level_callback(int );
extern bool wilderness_init_callback();
extern bool generate_wilderness_callback(int ,int );
extern bool enter_wilderness_callback(int ,int );
extern bool leave_wilderness_callback(int ,int );
extern void store_examine_callback(object_type *);
extern bool monster_move_callback(int *,int );
extern void create_monster_callback(int );
extern void delete_monster_callback(int );
extern void copy_monster_callback(int ,int );
extern char inkey_borg_callback(bool ,bool ,bool ,bool );
extern char inkey_callback(char );
extern long get_world_callback();
extern long get_player_class_callback();
extern long get_player_realms_callback();
extern long get_player_race_callback();
extern bool get_player_flags_callback();
extern bool player_outfit_callback();
extern long sense_inventory_callback();
extern bool destroy_object_callback(object_type *,int );
extern PyObject *object_create_callback(object_type *);
extern PyObject *object_load_callback(char *);
extern bool object_eat_callback(object_type *);
extern bool object_browse_callback(object_type *);
extern bool object_cast_callback(object_type *);
extern cptr object_save_callback(object_type *);
extern void object_delete_callback(object_type *);
extern PyObject *object_copy_callback(object_type *,object_type *);
extern long get_object_level_callback(object_type *);
extern long get_object_cost_callback(object_type *);
extern cptr get_object_name_callback(object_type *);
extern char get_object_d_char_callback(object_type *);
extern char get_object_x_char_callback(object_type *);
extern byte get_object_d_attr_callback(object_type *);
extern byte get_object_x_attr_callback(object_type *);
extern bool get_object_aware_callback(object_type *);
extern bool get_object_tried_callback(object_type *);
extern bool free_object_kind_list_callback();
extern bool init_object_kind_list_callback();
extern bool use_skill_callback();
extern cptr get_script_window_line(int );
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_game_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":new_game_callback")) 
        return NULL;
    new_game_callback();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_load_game_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:load_game_callback",&_arg0)) 
        return NULL;
    load_game_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_save_game_callback(PyObject *self, PyObject *args) {
    cptr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":save_game_callback")) 
        return NULL;
    _result = (cptr *) malloc(sizeof(cptr ));
    *(_result) = save_game_callback();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_cptr_p);
    return _resultobj;
}

static PyObject *_wrap_play_game_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":play_game_callback")) 
        return NULL;
    play_game_callback();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_eat_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:eat_callback",&_arg0)) 
        return NULL;
    eat_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_kill_monster_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:kill_monster_callback",&_arg0)) 
        return NULL;
    kill_monster_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_player_move_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:player_move_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )player_move_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_cmd_open_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:cmd_open_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )cmd_open_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_cmd_search_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:cmd_search_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )cmd_search_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_cmd_feeling_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"i:cmd_feeling_callback",&_arg0)) 
        return NULL;
    _result = (bool )cmd_feeling_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_cmd_go_up_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":cmd_go_up_callback")) 
        return NULL;
    _result = (bool )cmd_go_up_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_building_command_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:building_command_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )building_command_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_player_enter_grid_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:player_enter_grid_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )player_enter_grid_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_player_search_grid_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:player_search_grid_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )player_search_grid_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_generate_level_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"i:generate_level_callback",&_arg0)) 
        return NULL;
    _result = (bool )generate_level_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_leave_level_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:leave_level_callback",&_arg0)) 
        return NULL;
    leave_level_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_enter_level_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:enter_level_callback",&_arg0)) 
        return NULL;
    enter_level_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_wilderness_init_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":wilderness_init_callback")) 
        return NULL;
    _result = (bool )wilderness_init_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_generate_wilderness_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:generate_wilderness_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )generate_wilderness_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_enter_wilderness_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:enter_wilderness_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )enter_wilderness_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_leave_wilderness_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:leave_wilderness_callback",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )leave_wilderness_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_store_examine_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:store_examine_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    store_examine_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_monster_move_callback(PyObject *self, PyObject *args) {
    int  *_arg0,_arg1;
    PyObject  *_resultobj,*_argo0=0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"Oi:monster_move_callback",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_int_p,1)) == -1) return NULL;
    _result = (bool )monster_move_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_create_monster_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:create_monster_callback",&_arg0)) 
        return NULL;
    create_monster_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_delete_monster_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:delete_monster_callback",&_arg0)) 
        return NULL;
    delete_monster_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_copy_monster_callback(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:copy_monster_callback",&_arg0,&_arg1)) 
        return NULL;
    copy_monster_callback(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_inkey_borg_callback(PyObject *self, PyObject *args) {
    int tempbool0,tempbool1,tempbool2,tempbool3;
    PyObject  *_resultobj;
    char  _result;
    bool  _arg0,_arg1,_arg2,_arg3;
    self = self;
    if(!PyArg_ParseTuple(args,"iiii:inkey_borg_callback",&tempbool0,&tempbool1,&tempbool2,&tempbool3)) 
        return NULL;
    _arg0 = (bool ) tempbool0;
    _arg1 = (bool ) tempbool1;
    _arg2 = (bool ) tempbool2;
    _arg3 = (bool ) tempbool3;
    _result = (char )inkey_borg_callback(_arg0,_arg1,_arg2,_arg3);
    _resultobj = Py_BuildValue("c",_result);
    return _resultobj;
}

static PyObject *_wrap_inkey_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  _result,_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"c:inkey_callback",&_arg0)) 
        return NULL;
    _result = (char )inkey_callback(_arg0);
    _resultobj = Py_BuildValue("c",_result);
    return _resultobj;
}

static PyObject *_wrap_get_world_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":get_world_callback")) 
        return NULL;
    _result = (long )get_world_callback();
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_get_player_class_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":get_player_class_callback")) 
        return NULL;
    _result = (long )get_player_class_callback();
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_get_player_realms_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":get_player_realms_callback")) 
        return NULL;
    _result = (long )get_player_realms_callback();
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_get_player_race_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":get_player_race_callback")) 
        return NULL;
    _result = (long )get_player_race_callback();
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_get_player_flags_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":get_player_flags_callback")) 
        return NULL;
    _result = (bool )get_player_flags_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_player_outfit_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":player_outfit_callback")) 
        return NULL;
    _result = (bool )player_outfit_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_sense_inventory_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":sense_inventory_callback")) 
        return NULL;
    _result = (long )sense_inventory_callback();
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_destroy_object_callback(PyObject *self, PyObject *args) {
    int  _arg1;
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"Oi:destroy_object_callback",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (bool )destroy_object_callback(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_object_create_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_result,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:object_create_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (PyObject *)object_create_callback(_arg0);
    _resultobj = SWIG_NewPointerObj((void *) _result, SWIGTYPE_PyObject_p);
    return _resultobj;
}

static PyObject *_wrap_object_load_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_result;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:object_load_callback",&_arg0)) 
        return NULL;
    _result = (PyObject *)object_load_callback(_arg0);
    _resultobj = SWIG_NewPointerObj((void *) _result, SWIGTYPE_PyObject_p);
    return _resultobj;
}

static PyObject *_wrap_object_eat_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:object_eat_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (bool )object_eat_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_object_browse_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:object_browse_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (bool )object_browse_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_object_cast_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:object_cast_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (bool )object_cast_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_object_save_callback(PyObject *self, PyObject *args) {
    cptr  *_result;
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:object_save_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (cptr *) malloc(sizeof(cptr ));
    *(_result) = object_save_callback(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_cptr_p);
    return _resultobj;
}

static PyObject *_wrap_object_delete_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:object_delete_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    object_delete_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_object_copy_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_result,*_argo0=0,*_argo1=0;
    object_type  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"OO:object_copy_callback",&_argo0,&_argo1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(_argo1,(void **) &_arg1,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (PyObject *)object_copy_callback(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *) _result, SWIGTYPE_PyObject_p);
    return _resultobj;
}

static PyObject *_wrap_get_object_level_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_level_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (long )get_object_level_callback(_arg0);
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_get_object_cost_callback(PyObject *self, PyObject *args) {
    long  _result;
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_cost_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (long )get_object_cost_callback(_arg0);
    _resultobj = Py_BuildValue("l",_result);
    return _resultobj;
}

static PyObject *_wrap_get_object_name_callback(PyObject *self, PyObject *args) {
    cptr  *_result;
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_name_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (cptr *) malloc(sizeof(cptr ));
    *(_result) = get_object_name_callback(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_cptr_p);
    return _resultobj;
}

static PyObject *_wrap_get_object_d_char_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    char  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_d_char_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (char )get_object_d_char_callback(_arg0);
    _resultobj = Py_BuildValue("c",_result);
    return _resultobj;
}

static PyObject *_wrap_get_object_x_char_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    char  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_x_char_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (char )get_object_x_char_callback(_arg0);
    _resultobj = Py_BuildValue("c",_result);
    return _resultobj;
}

static PyObject *_wrap_get_object_d_attr_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    byte  *_result;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_d_attr_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (byte *) malloc(sizeof(byte ));
    *(_result) = get_object_d_attr_callback(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_byte_p);
    return _resultobj;
}

static PyObject *_wrap_get_object_x_attr_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    byte  *_result;
    object_type  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_x_attr_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (byte *) malloc(sizeof(byte ));
    *(_result) = get_object_x_attr_callback(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_byte_p);
    return _resultobj;
}

static PyObject *_wrap_get_object_aware_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_aware_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (bool )get_object_aware_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_object_tried_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj,*_argo0=0;
    object_type  *_arg0;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:get_object_tried_callback",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_object_type_p,1)) == -1) return NULL;
    _result = (bool )get_object_tried_callback(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_free_object_kind_list_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":free_object_kind_list_callback")) 
        return NULL;
    _result = (bool )free_object_kind_list_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_init_object_kind_list_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":init_object_kind_list_callback")) 
        return NULL;
    _result = (bool )init_object_kind_list_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_use_skill_callback(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":use_skill_callback")) 
        return NULL;
    _result = (bool )use_skill_callback();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_script_window_line(PyObject *self, PyObject *args) {
    int  _arg0;
    cptr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:get_script_window_line",&_arg0)) 
        return NULL;
    _result = (cptr *) malloc(sizeof(cptr ));
    *(_result) = get_script_window_line(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_cptr_p);
    return _resultobj;
}

static PyObject *_wrap_set_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj,*_arg1,*_obj1=0;
    self = self;
    if(!PyArg_ParseTuple(args,"iO:set_callback",&_arg0,&_obj1)) 
        return NULL;
{
	if (!PyCallable_Check(_obj1))
	{
		PyErr_SetString(PyExc_TypeError, "Need a callable object!");
		return NULL;
	}
	_arg1 = _obj1;
}
    set_callback(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_get_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj,*_result;
    self = self;
    if(!PyArg_ParseTuple(args,"i:get_callback",&_arg0)) 
        return NULL;
    _result = (PyObject *)get_callback(_arg0);
{
	_resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_remove_callback(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:remove_callback",&_arg0)) 
        return NULL;
    remove_callback(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef eventcMethods[] = {
	 { "remove_callback", _wrap_remove_callback, METH_VARARGS },
	 { "get_callback", _wrap_get_callback, METH_VARARGS },
	 { "set_callback", _wrap_set_callback, METH_VARARGS },
	 { "get_script_window_line", _wrap_get_script_window_line, METH_VARARGS },
	 { "use_skill_callback", _wrap_use_skill_callback, METH_VARARGS },
	 { "init_object_kind_list_callback", _wrap_init_object_kind_list_callback, METH_VARARGS },
	 { "free_object_kind_list_callback", _wrap_free_object_kind_list_callback, METH_VARARGS },
	 { "get_object_tried_callback", _wrap_get_object_tried_callback, METH_VARARGS },
	 { "get_object_aware_callback", _wrap_get_object_aware_callback, METH_VARARGS },
	 { "get_object_x_attr_callback", _wrap_get_object_x_attr_callback, METH_VARARGS },
	 { "get_object_d_attr_callback", _wrap_get_object_d_attr_callback, METH_VARARGS },
	 { "get_object_x_char_callback", _wrap_get_object_x_char_callback, METH_VARARGS },
	 { "get_object_d_char_callback", _wrap_get_object_d_char_callback, METH_VARARGS },
	 { "get_object_name_callback", _wrap_get_object_name_callback, METH_VARARGS },
	 { "get_object_cost_callback", _wrap_get_object_cost_callback, METH_VARARGS },
	 { "get_object_level_callback", _wrap_get_object_level_callback, METH_VARARGS },
	 { "object_copy_callback", _wrap_object_copy_callback, METH_VARARGS },
	 { "object_delete_callback", _wrap_object_delete_callback, METH_VARARGS },
	 { "object_save_callback", _wrap_object_save_callback, METH_VARARGS },
	 { "object_cast_callback", _wrap_object_cast_callback, METH_VARARGS },
	 { "object_browse_callback", _wrap_object_browse_callback, METH_VARARGS },
	 { "object_eat_callback", _wrap_object_eat_callback, METH_VARARGS },
	 { "object_load_callback", _wrap_object_load_callback, METH_VARARGS },
	 { "object_create_callback", _wrap_object_create_callback, METH_VARARGS },
	 { "destroy_object_callback", _wrap_destroy_object_callback, METH_VARARGS },
	 { "sense_inventory_callback", _wrap_sense_inventory_callback, METH_VARARGS },
	 { "player_outfit_callback", _wrap_player_outfit_callback, METH_VARARGS },
	 { "get_player_flags_callback", _wrap_get_player_flags_callback, METH_VARARGS },
	 { "get_player_race_callback", _wrap_get_player_race_callback, METH_VARARGS },
	 { "get_player_realms_callback", _wrap_get_player_realms_callback, METH_VARARGS },
	 { "get_player_class_callback", _wrap_get_player_class_callback, METH_VARARGS },
	 { "get_world_callback", _wrap_get_world_callback, METH_VARARGS },
	 { "inkey_callback", _wrap_inkey_callback, METH_VARARGS },
	 { "inkey_borg_callback", _wrap_inkey_borg_callback, METH_VARARGS },
	 { "copy_monster_callback", _wrap_copy_monster_callback, METH_VARARGS },
	 { "delete_monster_callback", _wrap_delete_monster_callback, METH_VARARGS },
	 { "create_monster_callback", _wrap_create_monster_callback, METH_VARARGS },
	 { "monster_move_callback", _wrap_monster_move_callback, METH_VARARGS },
	 { "store_examine_callback", _wrap_store_examine_callback, METH_VARARGS },
	 { "leave_wilderness_callback", _wrap_leave_wilderness_callback, METH_VARARGS },
	 { "enter_wilderness_callback", _wrap_enter_wilderness_callback, METH_VARARGS },
	 { "generate_wilderness_callback", _wrap_generate_wilderness_callback, METH_VARARGS },
	 { "wilderness_init_callback", _wrap_wilderness_init_callback, METH_VARARGS },
	 { "enter_level_callback", _wrap_enter_level_callback, METH_VARARGS },
	 { "leave_level_callback", _wrap_leave_level_callback, METH_VARARGS },
	 { "generate_level_callback", _wrap_generate_level_callback, METH_VARARGS },
	 { "player_search_grid_callback", _wrap_player_search_grid_callback, METH_VARARGS },
	 { "player_enter_grid_callback", _wrap_player_enter_grid_callback, METH_VARARGS },
	 { "building_command_callback", _wrap_building_command_callback, METH_VARARGS },
	 { "cmd_go_up_callback", _wrap_cmd_go_up_callback, METH_VARARGS },
	 { "cmd_feeling_callback", _wrap_cmd_feeling_callback, METH_VARARGS },
	 { "cmd_search_callback", _wrap_cmd_search_callback, METH_VARARGS },
	 { "cmd_open_callback", _wrap_cmd_open_callback, METH_VARARGS },
	 { "player_move_callback", _wrap_player_move_callback, METH_VARARGS },
	 { "kill_monster_callback", _wrap_kill_monster_callback, METH_VARARGS },
	 { "eat_callback", _wrap_eat_callback, METH_VARARGS },
	 { "play_game_callback", _wrap_play_game_callback, METH_VARARGS },
	 { "save_game_callback", _wrap_save_game_callback, METH_VARARGS },
	 { "load_game_callback", _wrap_load_game_callback, METH_VARARGS },
	 { "new_game_callback", _wrap_new_game_callback, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
static _swig_type_info _swigt__object_type_p[] = {{"_object_type_p",0},{"_object_type_p",0},{0}};
static _swig_type_info _swigt__int_p[] = {{"_int_p",0},{"_int_p",0},{0}};
static _swig_type_info _swigt__cptr_p[] = {{"_cptr_p",0},{"_cptr_p",0},{0}};
static _swig_type_info _swigt__PyObject_p[] = {{"_PyObject_p",0},{"_PyObject_p",0},{0}};
static _swig_type_info _swigt__byte_p[] = {{"_byte_p",0},{"_byte_p",0},{0}};

static _swig_type_info *_swig_types_initial[] = {
_swigt__object_type_p, 
_swigt__int_p, 
_swigt__cptr_p, 
_swigt__PyObject_p, 
_swigt__byte_p, 
0
};

static _swig_const_info _swig_const_table[] = {
    { SWIG_PY_INT,     "NEW_GAME_EVENT", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "LOAD_GAME_EVENT", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "SAVE_GAME_EVENT", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "CMD_EAT_EVENT", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "PLAYER_MOVE_EVENT", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "CMD_OPEN_EVENT", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "CMD_SEARCH_EVENT", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "PLAYER_SEARCH_GRID_EVENT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "CMD_FEELING_EVENT", (long) 9, 0, 0, 0},
    { SWIG_PY_INT,     "CMD_GO_UP_EVENT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "KILL_MONSTER_EVENT", (long) 11, 0, 0, 0},
    { SWIG_PY_INT,     "BUILDING_COMMAND_EVENT", (long) 12, 0, 0, 0},
    { SWIG_PY_INT,     "LEAVE_LEVEL_EVENT", (long) 13, 0, 0, 0},
    { SWIG_PY_INT,     "PLAYER_ENTER_GRID_EVENT", (long) 14, 0, 0, 0},
    { SWIG_PY_INT,     "ENTER_LEVEL_EVENT", (long) 15, 0, 0, 0},
    { SWIG_PY_INT,     "GENERATE_LEVEL_EVENT", (long) 16, 0, 0, 0},
    { SWIG_PY_INT,     "GENERATE_WILDERNESS_EVENT", (long) 17, 0, 0, 0},
    { SWIG_PY_INT,     "ENTER_WILDERNESS_EVENT", (long) 18, 0, 0, 0},
    { SWIG_PY_INT,     "LEAVE_WILDERNESS_EVENT", (long) 19, 0, 0, 0},
    { SWIG_PY_INT,     "STORE_EXAMINE_EVENT", (long) 20, 0, 0, 0},
    { SWIG_PY_INT,     "MONSTER_MOVE_EVENT", (long) 21, 0, 0, 0},
    { SWIG_PY_INT,     "CREATE_MONSTER_EVENT", (long) 22, 0, 0, 0},
    { SWIG_PY_INT,     "DELETE_MONSTER_EVENT", (long) 23, 0, 0, 0},
    { SWIG_PY_INT,     "INKEY_BORG_EVENT", (long) 24, 0, 0, 0},
    { SWIG_PY_INT,     "INKEY_EVENT", (long) 25, 0, 0, 0},
    { SWIG_PY_INT,     "GET_PLAYER_CLASS_EVENT", (long) 26, 0, 0, 0},
    { SWIG_PY_INT,     "GET_PLAYER_FLAGS_EVENT", (long) 27, 0, 0, 0},
    { SWIG_PY_INT,     "SENSE_INVENTORY_EVENT", (long) 28, 0, 0, 0},
    { SWIG_PY_INT,     "DESTROY_OBJECT_EVENT", (long) 29, 0, 0, 0},
    { SWIG_PY_INT,     "GET_PLAYER_RACE_EVENT", (long) 30, 0, 0, 0},
    { SWIG_PY_INT,     "OBJECT_CREATE_EVENT", (long) 31, 0, 0, 0},
    { SWIG_PY_INT,     "OBJECT_LOAD_EVENT", (long) 32, 0, 0, 0},
    { SWIG_PY_INT,     "PLAYER_OUTFIT_EVENT", (long) 33, 0, 0, 0},
    { SWIG_PY_INT,     "WILDERNESS_INIT_EVENT", (long) 34, 0, 0, 0},
    { SWIG_PY_INT,     "FREE_OBJECT_KIND_LIST_EVENT", (long) 35, 0, 0, 0},
    { SWIG_PY_INT,     "INIT_OBJECT_KIND_LIST_EVENT", (long) 36, 0, 0, 0},
    { SWIG_PY_INT,     "GET_PLAYER_REALMS_EVENT", (long) 37, 0, 0, 0},
    { SWIG_PY_INT,     "GET_WORLD_EVENT", (long) 38, 0, 0, 0},
    { SWIG_PY_INT,     "COPY_MONSTER_EVENT", (long) 39, 0, 0, 0},
    { SWIG_PY_INT,     "USE_SKILL_EVENT", (long) 40, 0, 0, 0},
    { SWIG_PY_INT,     "GET_SCRIPT_WINDOW_LINE_EVENT", (long) 41, 0, 0, 0},
    { SWIG_PY_INT,     "PLAY_GAME_EVENT", (long) 42, 0, 0, 0},
    { SWIG_PY_INT,     "MAX_EVENT", (long) 43, 0, 0, 0},
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initeventc(void) {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("eventc", eventcMethods);
	 d = PyModule_GetDict(m);
    {
        int i;
        for (i = 0; _swig_types_initial[i]; i++) {
            _swig_types[i] = SWIG_TypeRegister(_swig_types_initial[i]);
        }
    }
    SWIG_InstallConstants(d,_swig_const_table);

}
