/*
 * FILE : io_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
#ifdef __cplusplus
}
#endif

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}



/*****************************************************************************
 * $Header$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    initio

#define SWIG_name    "io"


#include "angband.h"

char get_line_tmp[1024];

cptr get_line(void)
{
	if (get_string("", get_line_tmp, 1024))
		return get_line_tmp;
	else
		return "\n";

	p_ptr->window |= (PW_SCRIPT);
}

extern const char *get_line();
extern bool show_file(const char *,const char *,int ,int );
extern errr path_parse(char *,int ,const char *);
extern errr path_temp(char *,int );
extern errr path_build(char *,int ,const char *,const char *);
extern FILE *my_fopen(const char *,const char *);
extern errr my_fgets(FILE *,char *,huge );
extern errr my_fputs(FILE *,const char *,huge );
extern errr my_fclose(FILE *);
extern errr fd_kill(const char *);
extern errr fd_move(const char *,const char *);
extern errr fd_copy(const char *,const char *);
extern int fd_make(const char *,int );
extern int fd_open(const char *,int );
extern errr fd_lock(int ,int );
extern errr fd_seek(int ,huge );
extern errr fd_chop(int ,huge );
extern errr fd_read(int ,char *,huge );
extern errr fd_write(int ,const char *,huge );
extern errr fd_close(int );
extern void flush();
extern void bell();
extern void sound(int );
extern void move_cursor(int ,int );
extern void text_to_ascii(char *,const char *);
extern void ascii_to_text(char *,const char *);
extern errr macro_add(const char *,const char *);
extern sint macro_find_exact(const char *);
extern char inkey();
extern const char *quark_str(s16b );
extern s16b quark_add(const char *);
extern s16b message_num();
extern const char *message_str(int );
extern byte message_color(int );
extern void message_add(const char *,byte );
extern void msg_print(const char *);
extern void msg_print_color(byte ,const char *);
extern void screen_save();
extern void screen_load();
extern void c_put_str(byte ,const char *,int ,int );
extern void put_str(const char *,int ,int );
extern void c_prt(byte ,const char *,int ,int );
extern void prt(const char *,int ,int );
extern void c_roff(byte ,const char *);
extern void roff(const char *);
extern void clear_from(int );
extern bool askfor_aux(char *,int );
extern bool get_string(const char *,char *,int );
extern bool get_check(const char *);
extern bool get_com(const char *,char *);
extern s16b get_quantity(const char *,int );
extern void pause_line(int );
extern void request_command(int );
extern bool is_a_vowel(int );
extern int get_keymap_dir(char );
extern bool get_aim_dir(int *);
extern term * Term; 
extern errr Term_user(int );
extern errr Term_xtra(int ,int );
extern void Term_queue_chars(int ,int ,int ,byte ,const char *);
extern errr Term_fresh();
extern errr Term_set_cursor(int );
extern errr Term_gotoxy(int ,int );
extern errr Term_draw(int ,int ,byte ,char );
extern errr Term_addch(byte ,char );
extern errr Term_addstr(int ,byte ,const char *);
extern errr Term_putch(int ,int ,byte ,char );
extern errr Term_putstr(int ,int ,int ,byte ,const char *);
extern errr Term_erase(int ,int ,int );
extern errr Term_clear();
extern errr Term_redraw();
extern errr Term_get_cursor(int *);
extern errr Term_get_size(int *,int *);
extern errr Term_locate(int *,int *);
extern errr Term_what(int ,int ,byte *,char *);
extern errr Term_flush();
extern errr Term_keypress(int );
extern errr Term_key_push(int );
extern errr Term_inkey(char *,bool ,bool );
extern errr Term_save();
extern errr Term_load();
extern errr Term_exchange();
extern errr Term_resize(int ,int );
extern errr Term_activate(term *);
extern errr term_nuke(term *);
extern errr term_init(term *,int ,int ,int );
extern u32b  option_mask[8]; 
extern u32b  window_flag[8]; 
extern u32b  window_mask[8]; 
extern char  angband_term_name[8][16]; 
extern byte  angband_color_table[256][4]; 
extern char  angband_sound_name[(65)][16]; 
static PyObject *_wrap_get_line(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;

    self = self;
    if(!PyArg_ParseTuple(args,":get_line")) 
        return NULL;
    _result = (char *)get_line();
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_show_file(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    char * _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;

    self = self;
    if(!PyArg_ParseTuple(args,"ssii:show_file",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (bool )show_file(_arg0,_arg1,_arg2,_arg3);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_path_parse(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    int  _arg1;
    char * _arg2;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"sis:path_parse",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = path_parse(_arg0,_arg1,_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_path_temp(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    int  _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"si:path_temp",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = path_temp(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_path_build(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    int  _arg1;
    char * _arg2;
    char * _arg3;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"siss:path_build",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = path_build(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_my_fopen(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    FILE * _result;
    char * _arg0;
    char * _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:my_fopen",&_arg0,&_arg1)) 
        return NULL;
    _result = (FILE *)my_fopen(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_FILE_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_my_fgets(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    FILE * _arg0;
    char * _arg1;
    huge * _arg2;
    char * _argc0 = 0;
    char * _argc2 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"sss:my_fgets",&_argc0,&_arg1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_FILE_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of my_fgets. Expected _FILE_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_huge_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of my_fgets. Expected _huge_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = my_fgets(_arg0,_arg1,*_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_my_fputs(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    FILE * _arg0;
    char * _arg1;
    huge * _arg2;
    char * _argc0 = 0;
    char * _argc2 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"sss:my_fputs",&_argc0,&_arg1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_FILE_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of my_fputs. Expected _FILE_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_huge_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of my_fputs. Expected _huge_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = my_fputs(_arg0,_arg1,*_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_my_fclose(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    FILE * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:my_fclose",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_FILE_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of my_fclose. Expected _FILE_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = my_fclose(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_kill(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:fd_kill",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_kill(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_move(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    char * _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:fd_move",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_move(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_copy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    char * _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:fd_copy",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_copy(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_make(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    char * _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"si:fd_make",&_arg0,&_arg1)) 
        return NULL;
    _result = (int )fd_make(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fd_open(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    char * _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"si:fd_open",&_arg0,&_arg1)) 
        return NULL;
    _result = (int )fd_open(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fd_lock(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ii:fd_lock",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_lock(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_seek(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    huge * _arg1;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"is:fd_seek",&_arg0,&_argc1)) 
        return NULL;
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_huge_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fd_seek. Expected _huge_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_seek(_arg0,*_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_chop(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    huge * _arg1;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"is:fd_chop",&_arg0,&_argc1)) 
        return NULL;
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_huge_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of fd_chop. Expected _huge_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_chop(_arg0,*_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_read(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char * _arg1;
    huge * _arg2;
    char * _argc2 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iss:fd_read",&_arg0,&_arg1,&_argc2)) 
        return NULL;
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_huge_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of fd_read. Expected _huge_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_read(_arg0,_arg1,*_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_write(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char * _arg1;
    huge * _arg2;
    char * _argc2 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iss:fd_write",&_arg0,&_arg1,&_argc2)) 
        return NULL;
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_huge_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of fd_write. Expected _huge_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_write(_arg0,_arg1,*_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_fd_close(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:fd_close",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_close(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_flush(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":flush")) 
        return NULL;
    flush();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_bell(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":bell")) 
        return NULL;
    bell();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_sound(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:sound",&_arg0)) 
        return NULL;
    sound(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_move_cursor(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ii:move_cursor",&_arg0,&_arg1)) 
        return NULL;
    move_cursor(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_text_to_ascii(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;
    char * _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:text_to_ascii",&_arg0,&_arg1)) 
        return NULL;
    text_to_ascii(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_ascii_to_text(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;
    char * _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:ascii_to_text",&_arg0,&_arg1)) 
        return NULL;
    ascii_to_text(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_macro_add(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    char * _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:macro_add",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = macro_add(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_macro_find_exact(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    sint * _result;
    char * _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:macro_find_exact",&_arg0)) 
        return NULL;
    _result = (sint *) malloc(sizeof(sint ));
    *(_result) = macro_find_exact(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_sint_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_inkey(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char  _result;

    self = self;
    if(!PyArg_ParseTuple(args,":inkey")) 
        return NULL;
    _result = (char )inkey();
    _resultobj = Py_BuildValue("c",_result);
    return _resultobj;
}

static PyObject *_wrap_quark_str(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    s16b  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"h:quark_str",&_arg0)) 
        return NULL;
    _result = (char *)quark_str(_arg0);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_quark_add(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    char * _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:quark_add",&_arg0)) 
        return NULL;
    _result = (s16b )quark_add(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_message_num(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;

    self = self;
    if(!PyArg_ParseTuple(args,":message_num")) 
        return NULL;
    _result = (s16b )message_num();
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_message_str(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _result;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:message_str",&_arg0)) 
        return NULL;
    _result = (char *)message_str(_arg0);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_message_color(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:message_color",&_arg0)) 
        return NULL;
    _result = (byte )message_color(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static PyObject *_wrap_message_add(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;
    byte  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"sb:message_add",&_arg0,&_arg1)) 
        return NULL;
    message_add(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_msg_print(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:msg_print",&_arg0)) 
        return NULL;
    msg_print(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_msg_print_color(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _arg0;
    char * _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"bs:msg_print_color",&_arg0,&_arg1)) 
        return NULL;
    msg_print_color(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_screen_save(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":screen_save")) 
        return NULL;
    screen_save();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_screen_load(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":screen_load")) 
        return NULL;
    screen_load();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_c_put_str(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;

    self = self;
    if(!PyArg_ParseTuple(args,"bsii:c_put_str",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    c_put_str(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_put_str(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;
    int  _arg1;
    int  _arg2;

    self = self;
    if(!PyArg_ParseTuple(args,"sii:put_str",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    put_str(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_c_prt(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;

    self = self;
    if(!PyArg_ParseTuple(args,"bsii:c_prt",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    c_prt(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_prt(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;
    int  _arg1;
    int  _arg2;

    self = self;
    if(!PyArg_ParseTuple(args,"sii:prt",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    prt(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_c_roff(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _arg0;
    char * _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"bs:c_roff",&_arg0,&_arg1)) 
        return NULL;
    c_roff(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_roff(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:roff",&_arg0)) 
        return NULL;
    roff(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_clear_from(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:clear_from",&_arg0)) 
        return NULL;
    clear_from(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_askfor_aux(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    char * _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"si:askfor_aux",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )askfor_aux(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_string(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    char * _arg0;
    char * _arg1;
    int  _arg2;

    self = self;
    if(!PyArg_ParseTuple(args,"ssi:get_string",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (bool )get_string(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_check(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    char * _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:get_check",&_arg0)) 
        return NULL;
    _result = (bool )get_check(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_com(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    char * _arg0;
    char * _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:get_com",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )get_com(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_quantity(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    char * _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"si:get_quantity",&_arg0,&_arg1)) 
        return NULL;
    _result = (s16b )get_quantity(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_pause_line(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:pause_line",&_arg0)) 
        return NULL;
    pause_line(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_request_command(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:request_command",&_arg0)) 
        return NULL;
    request_command(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_is_a_vowel(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    int  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:is_a_vowel",&_arg0)) 
        return NULL;
    _result = (bool )is_a_vowel(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_keymap_dir(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    char  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"c:get_keymap_dir",&_arg0)) 
        return NULL;
    _result = (int )get_keymap_dir(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_aim_dir(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;
    int * _arg0;
    int  temp;

    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":get_aim_dir")) 
        return NULL;
    _result = (bool )get_aim_dir(_arg0);
    _resultobj = Py_BuildValue("i",_result);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static int _wrap_Term_set(PyObject *val) {
    char * tval;
    term * temp;

    tval = (char *) PyString_AsString(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'Term'(term *)");
        return 1; 
    }
    if (tval) {
        if (SWIG_GetPtr(tval,(void **) &temp,"_term_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in value of Term. Expected _term_p.");
        return 1;
        }
    }
    Term = temp;
    return 0;
}

static PyObject *_wrap_Term_get() {
    PyObject * pyobj;
    char ptemp[128];

    SWIG_MakePtr(ptemp, (char *) Term,"_term_p");
    pyobj = PyString_FromString(ptemp);
    return pyobj;
}

static PyObject *_wrap_Term_user(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_user",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_user(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_xtra(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ii:Term_xtra",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_xtra(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_queue_chars(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    byte  _arg3;
    char * _arg4;

    self = self;
    if(!PyArg_ParseTuple(args,"iiibs:Term_queue_chars",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    Term_queue_chars(_arg0,_arg1,_arg2,_arg3,_arg4);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Term_fresh(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_fresh")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_fresh();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_set_cursor(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_set_cursor",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_set_cursor(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_gotoxy(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ii:Term_gotoxy",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_gotoxy(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_draw(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    byte  _arg2;
    char  _arg3;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iibc:Term_draw",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_draw(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_addch(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    byte  _arg0;
    char  _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"bc:Term_addch",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_addch(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_addstr(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    byte  _arg1;
    char * _arg2;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ibs:Term_addstr",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_addstr(_arg0,_arg1,_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_putch(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    byte  _arg2;
    char  _arg3;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iibc:Term_putch",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_putch(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_putstr(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    byte  _arg3;
    char * _arg4;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiibs:Term_putstr",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_putstr(_arg0,_arg1,_arg2,_arg3,_arg4);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_erase(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iii:Term_erase",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_erase(_arg0,_arg1,_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_clear(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_clear")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_clear();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_redraw(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_redraw")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_redraw();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_get_cursor(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int * _arg0;
    int  temp;
    char _ptemp[128];

    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":Term_get_cursor")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_get_cursor(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static PyObject *_wrap_Term_get_size(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int * _arg0;
    int  temp;
    int * _arg1;
    int  temp0;
    char _ptemp[128];

    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
{
	_arg1 = &temp0; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":Term_get_size")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_get_size(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
{
	PyObject *o;

	o = PyInt_FromLong(*_arg1);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static PyObject *_wrap_Term_locate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int * _arg0;
    int  temp;
    int * _arg1;
    int  temp0;
    char _ptemp[128];

    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
{
	_arg1 = &temp0; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":Term_locate")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_locate(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
{
	PyObject *o;

	o = PyInt_FromLong(*_arg1);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static PyObject *_wrap_Term_what(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    byte * _arg2;
    char * _arg3;
    char * _argc2 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiss:Term_what",&_arg0,&_arg1,&_argc2,&_arg3)) 
        return NULL;
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_byte_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of Term_what. Expected _byte_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_what(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_flush(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_flush")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_flush();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_keypress(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_keypress",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_keypress(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_key_push(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_key_push",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_key_push(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_inkey(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char * _arg0;
    bool  _arg1;
    bool  _arg2;
    int tempbool1;
    int tempbool2;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"sii:Term_inkey",&_arg0,&tempbool1,&tempbool2)) 
        return NULL;
    _arg1 = (bool ) tempbool1;
    _arg2 = (bool ) tempbool2;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_inkey(_arg0,_arg1,_arg2);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_save(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_save")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_save();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_load(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_load")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_load();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_exchange(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":Term_exchange")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_exchange();
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_resize(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    int  _arg0;
    int  _arg1;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ii:Term_resize",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_resize(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Term_activate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    term * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:Term_activate",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_term_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Term_activate. Expected _term_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_activate(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_term_nuke(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    term * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:term_nuke",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_term_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of term_nuke. Expected _term_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = term_nuke(_arg0);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_term_init(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    errr * _result;
    term * _arg0;
    int  _arg1;
    int  _arg2;
    int  _arg3;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"siii:term_init",&_argc0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_term_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of term_init. Expected _term_p.");
        return NULL;
        }
    }
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = term_init(_arg0,_arg1,_arg2,_arg3);
    SWIG_MakePtr(_ptemp, (void *) _result,"_errr_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static int _wrap_option_mask_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable option_mask is read-only.");
    return 1;
}

static PyObject *_wrap_option_mask_get() {
    PyObject * pyobj;

{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(option_mask[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_window_flag_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable window_flag is read-only.");
    return 1;
}

static PyObject *_wrap_window_flag_get() {
    PyObject * pyobj;

{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(window_flag[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_window_mask_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable window_mask is read-only.");
    return 1;
}

static PyObject *_wrap_window_mask_get() {
    PyObject * pyobj;

{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(window_mask[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_angband_term_name_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable angband_term_name is read-only.");
    return 1;
}

static PyObject *_wrap_angband_term_name_get() {
    PyObject * pyobj;

{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyString_FromString(angband_term_name[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_angband_color_table_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable angband_color_table is read-only.");
    return 1;
}

static PyObject *_wrap_angband_color_table_get() {
    PyObject * pyobj;

{
	PyObject *tuple;
	int i, j;

	pyobj = PyList_New(256);

	for (i = 0; i < 256; i++)
	{
		tuple = PyTuple_New(4);

		for (j = 0; j < 4; j++)
			PyTuple_SetItem(tuple, j, PyInt_FromLong(angband_color_table[i][j]));

		PyList_SetItem(pyobj, i, tuple);
	}
}
    return pyobj;
}

static int _wrap_angband_sound_name_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable angband_sound_name is read-only.");
    return 1;
}

static PyObject *_wrap_angband_sound_name_get() {
    PyObject * pyobj;

{
	PyObject *o;
	int i;

	pyobj = PyList_New((65));

	for (i = 0; i < (65); i++)
	{
		o = PyString_FromString(angband_sound_name[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_inkey_base_set(PyObject *val) {
    bool  tval;

    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_base'(bool )");
        return 1; 
    }
    inkey_base = tval;
    return 0;
}

static PyObject *_wrap_inkey_base_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) inkey_base);
    return pyobj;
}

static int _wrap_inkey_xtra_set(PyObject *val) {
    bool  tval;

    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_xtra'(bool )");
        return 1; 
    }
    inkey_xtra = tval;
    return 0;
}

static PyObject *_wrap_inkey_xtra_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) inkey_xtra);
    return pyobj;
}

static int _wrap_inkey_scan_set(PyObject *val) {
    bool  tval;

    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_scan'(bool )");
        return 1; 
    }
    inkey_scan = tval;
    return 0;
}

static PyObject *_wrap_inkey_scan_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) inkey_scan);
    return pyobj;
}

static int _wrap_inkey_flag_set(PyObject *val) {
    bool  tval;

    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_flag'(bool )");
        return 1; 
    }
    inkey_flag = tval;
    return 0;
}

static PyObject *_wrap_inkey_flag_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) inkey_flag);
    return pyobj;
}

static PyMethodDef ioMethods[] = {
	 { "term_init", _wrap_term_init, 1 },
	 { "term_nuke", _wrap_term_nuke, 1 },
	 { "Term_activate", _wrap_Term_activate, 1 },
	 { "Term_resize", _wrap_Term_resize, 1 },
	 { "Term_exchange", _wrap_Term_exchange, 1 },
	 { "Term_load", _wrap_Term_load, 1 },
	 { "Term_save", _wrap_Term_save, 1 },
	 { "Term_inkey", _wrap_Term_inkey, 1 },
	 { "Term_key_push", _wrap_Term_key_push, 1 },
	 { "Term_keypress", _wrap_Term_keypress, 1 },
	 { "Term_flush", _wrap_Term_flush, 1 },
	 { "Term_what", _wrap_Term_what, 1 },
	 { "Term_locate", _wrap_Term_locate, 1 },
	 { "Term_get_size", _wrap_Term_get_size, 1 },
	 { "Term_get_cursor", _wrap_Term_get_cursor, 1 },
	 { "Term_redraw", _wrap_Term_redraw, 1 },
	 { "Term_clear", _wrap_Term_clear, 1 },
	 { "Term_erase", _wrap_Term_erase, 1 },
	 { "Term_putstr", _wrap_Term_putstr, 1 },
	 { "Term_putch", _wrap_Term_putch, 1 },
	 { "Term_addstr", _wrap_Term_addstr, 1 },
	 { "Term_addch", _wrap_Term_addch, 1 },
	 { "Term_draw", _wrap_Term_draw, 1 },
	 { "Term_gotoxy", _wrap_Term_gotoxy, 1 },
	 { "Term_set_cursor", _wrap_Term_set_cursor, 1 },
	 { "Term_fresh", _wrap_Term_fresh, 1 },
	 { "Term_queue_chars", _wrap_Term_queue_chars, 1 },
	 { "Term_xtra", _wrap_Term_xtra, 1 },
	 { "Term_user", _wrap_Term_user, 1 },
	 { "get_aim_dir", _wrap_get_aim_dir, 1 },
	 { "get_keymap_dir", _wrap_get_keymap_dir, 1 },
	 { "is_a_vowel", _wrap_is_a_vowel, 1 },
	 { "request_command", _wrap_request_command, 1 },
	 { "pause_line", _wrap_pause_line, 1 },
	 { "get_quantity", _wrap_get_quantity, 1 },
	 { "get_com", _wrap_get_com, 1 },
	 { "get_check", _wrap_get_check, 1 },
	 { "get_string", _wrap_get_string, 1 },
	 { "askfor_aux", _wrap_askfor_aux, 1 },
	 { "clear_from", _wrap_clear_from, 1 },
	 { "roff", _wrap_roff, 1 },
	 { "c_roff", _wrap_c_roff, 1 },
	 { "prt", _wrap_prt, 1 },
	 { "c_prt", _wrap_c_prt, 1 },
	 { "put_str", _wrap_put_str, 1 },
	 { "c_put_str", _wrap_c_put_str, 1 },
	 { "screen_load", _wrap_screen_load, 1 },
	 { "screen_save", _wrap_screen_save, 1 },
	 { "msg_print_color", _wrap_msg_print_color, 1 },
	 { "msg_print", _wrap_msg_print, 1 },
	 { "message_add", _wrap_message_add, 1 },
	 { "message_color", _wrap_message_color, 1 },
	 { "message_str", _wrap_message_str, 1 },
	 { "message_num", _wrap_message_num, 1 },
	 { "quark_add", _wrap_quark_add, 1 },
	 { "quark_str", _wrap_quark_str, 1 },
	 { "inkey", _wrap_inkey, 1 },
	 { "macro_find_exact", _wrap_macro_find_exact, 1 },
	 { "macro_add", _wrap_macro_add, 1 },
	 { "ascii_to_text", _wrap_ascii_to_text, 1 },
	 { "text_to_ascii", _wrap_text_to_ascii, 1 },
	 { "move_cursor", _wrap_move_cursor, 1 },
	 { "sound", _wrap_sound, 1 },
	 { "bell", _wrap_bell, 1 },
	 { "flush", _wrap_flush, 1 },
	 { "fd_close", _wrap_fd_close, 1 },
	 { "fd_write", _wrap_fd_write, 1 },
	 { "fd_read", _wrap_fd_read, 1 },
	 { "fd_chop", _wrap_fd_chop, 1 },
	 { "fd_seek", _wrap_fd_seek, 1 },
	 { "fd_lock", _wrap_fd_lock, 1 },
	 { "fd_open", _wrap_fd_open, 1 },
	 { "fd_make", _wrap_fd_make, 1 },
	 { "fd_copy", _wrap_fd_copy, 1 },
	 { "fd_move", _wrap_fd_move, 1 },
	 { "fd_kill", _wrap_fd_kill, 1 },
	 { "my_fclose", _wrap_my_fclose, 1 },
	 { "my_fputs", _wrap_my_fputs, 1 },
	 { "my_fgets", _wrap_my_fgets, 1 },
	 { "my_fopen", _wrap_my_fopen, 1 },
	 { "path_build", _wrap_path_build, 1 },
	 { "path_temp", _wrap_path_temp, 1 },
	 { "path_parse", _wrap_path_parse, 1 },
	 { "show_file", _wrap_show_file, 1 },
	 { "get_line", _wrap_get_line, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void,initio)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("io", ioMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"TERM_XTRA_EVENT", PyInt_FromLong((long) 1));
	 PyDict_SetItemString(d,"TERM_XTRA_FLUSH", PyInt_FromLong((long) 2));
	 PyDict_SetItemString(d,"TERM_XTRA_CLEAR", PyInt_FromLong((long) 3));
	 PyDict_SetItemString(d,"TERM_XTRA_SHAPE", PyInt_FromLong((long) 4));
	 PyDict_SetItemString(d,"TERM_XTRA_FROSH", PyInt_FromLong((long) 5));
	 PyDict_SetItemString(d,"TERM_XTRA_FRESH", PyInt_FromLong((long) 6));
	 PyDict_SetItemString(d,"TERM_XTRA_NOISE", PyInt_FromLong((long) 7));
	 PyDict_SetItemString(d,"TERM_XTRA_SOUND", PyInt_FromLong((long) 8));
	 PyDict_SetItemString(d,"TERM_XTRA_BORED", PyInt_FromLong((long) 9));
	 PyDict_SetItemString(d,"TERM_XTRA_REACT", PyInt_FromLong((long) 10));
	 PyDict_SetItemString(d,"TERM_XTRA_ALIVE", PyInt_FromLong((long) 11));
	 PyDict_SetItemString(d,"TERM_XTRA_LEVEL", PyInt_FromLong((long) 12));
	 PyDict_SetItemString(d,"TERM_XTRA_DELAY", PyInt_FromLong((long) 13));
	 PyDict_SetItemString(d,"cvar", SWIG_globals);
	 SWIG_addvarlink(SWIG_globals,"Term",_wrap_Term_get, _wrap_Term_set);
	 PyDict_SetItemString(d,"TERM_DARK", PyInt_FromLong((long) 0));
	 PyDict_SetItemString(d,"TERM_WHITE", PyInt_FromLong((long) 1));
	 PyDict_SetItemString(d,"TERM_SLATE", PyInt_FromLong((long) 2));
	 PyDict_SetItemString(d,"TERM_ORANGE", PyInt_FromLong((long) 3));
	 PyDict_SetItemString(d,"TERM_RED", PyInt_FromLong((long) 4));
	 PyDict_SetItemString(d,"TERM_GREEN", PyInt_FromLong((long) 5));
	 PyDict_SetItemString(d,"TERM_BLUE", PyInt_FromLong((long) 6));
	 PyDict_SetItemString(d,"TERM_UMBER", PyInt_FromLong((long) 7));
	 PyDict_SetItemString(d,"TERM_L_DARK", PyInt_FromLong((long) 8));
	 PyDict_SetItemString(d,"TERM_L_WHITE", PyInt_FromLong((long) 9));
	 PyDict_SetItemString(d,"TERM_VIOLET", PyInt_FromLong((long) 10));
	 PyDict_SetItemString(d,"TERM_YELLOW", PyInt_FromLong((long) 11));
	 PyDict_SetItemString(d,"TERM_L_RED", PyInt_FromLong((long) 12));
	 PyDict_SetItemString(d,"TERM_L_GREEN", PyInt_FromLong((long) 13));
	 PyDict_SetItemString(d,"TERM_L_BLUE", PyInt_FromLong((long) 14));
	 PyDict_SetItemString(d,"TERM_L_UMBER", PyInt_FromLong((long) 15));
	 PyDict_SetItemString(d,"SOUND_HIT", PyInt_FromLong((long) 1));
	 PyDict_SetItemString(d,"SOUND_MISS", PyInt_FromLong((long) 2));
	 PyDict_SetItemString(d,"SOUND_FLEE", PyInt_FromLong((long) 3));
	 PyDict_SetItemString(d,"SOUND_DROP", PyInt_FromLong((long) 4));
	 PyDict_SetItemString(d,"SOUND_KILL", PyInt_FromLong((long) 5));
	 PyDict_SetItemString(d,"SOUND_LEVEL", PyInt_FromLong((long) 6));
	 PyDict_SetItemString(d,"SOUND_DEATH", PyInt_FromLong((long) 7));
	 PyDict_SetItemString(d,"SOUND_STUDY", PyInt_FromLong((long) 8));
	 PyDict_SetItemString(d,"SOUND_TELEPORT", PyInt_FromLong((long) 9));
	 PyDict_SetItemString(d,"SOUND_SHOOT", PyInt_FromLong((long) 10));
	 PyDict_SetItemString(d,"SOUND_QUAFF", PyInt_FromLong((long) 11));
	 PyDict_SetItemString(d,"SOUND_ZAP", PyInt_FromLong((long) 12));
	 PyDict_SetItemString(d,"SOUND_WALK", PyInt_FromLong((long) 13));
	 PyDict_SetItemString(d,"SOUND_TPOTHER", PyInt_FromLong((long) 14));
	 PyDict_SetItemString(d,"SOUND_HITWALL", PyInt_FromLong((long) 15));
	 PyDict_SetItemString(d,"SOUND_EAT", PyInt_FromLong((long) 16));
	 PyDict_SetItemString(d,"SOUND_STORE1", PyInt_FromLong((long) 17));
	 PyDict_SetItemString(d,"SOUND_STORE2", PyInt_FromLong((long) 18));
	 PyDict_SetItemString(d,"SOUND_STORE3", PyInt_FromLong((long) 19));
	 PyDict_SetItemString(d,"SOUND_STORE4", PyInt_FromLong((long) 20));
	 PyDict_SetItemString(d,"SOUND_DIG", PyInt_FromLong((long) 21));
	 PyDict_SetItemString(d,"SOUND_OPENDOOR", PyInt_FromLong((long) 22));
	 PyDict_SetItemString(d,"SOUND_SHUTDOOR", PyInt_FromLong((long) 23));
	 PyDict_SetItemString(d,"SOUND_TPLEVEL", PyInt_FromLong((long) 24));
	 PyDict_SetItemString(d,"SOUND_SCROLL", PyInt_FromLong((long) 25));
	 PyDict_SetItemString(d,"SOUND_BUY", PyInt_FromLong((long) 26));
	 PyDict_SetItemString(d,"SOUND_SELL", PyInt_FromLong((long) 27));
	 PyDict_SetItemString(d,"SOUND_WARN", PyInt_FromLong((long) 28));
	 PyDict_SetItemString(d,"SOUND_ROCKET", PyInt_FromLong((long) 29));
	 PyDict_SetItemString(d,"SOUND_N_KILL", PyInt_FromLong((long) 30));
	 PyDict_SetItemString(d,"SOUND_U_KILL", PyInt_FromLong((long) 31));
	 PyDict_SetItemString(d,"SOUND_QUEST", PyInt_FromLong((long) 32));
	 PyDict_SetItemString(d,"SOUND_HEAL", PyInt_FromLong((long) 33));
	 PyDict_SetItemString(d,"SOUND_X_HEAL", PyInt_FromLong((long) 34));
	 PyDict_SetItemString(d,"SOUND_BITE", PyInt_FromLong((long) 35));
	 PyDict_SetItemString(d,"SOUND_CLAW", PyInt_FromLong((long) 36));
	 PyDict_SetItemString(d,"SOUND_M_SPELL", PyInt_FromLong((long) 37));
	 PyDict_SetItemString(d,"SOUND_SUMMON", PyInt_FromLong((long) 38));
	 PyDict_SetItemString(d,"SOUND_BREATH", PyInt_FromLong((long) 39));
	 PyDict_SetItemString(d,"SOUND_BALL", PyInt_FromLong((long) 40));
	 PyDict_SetItemString(d,"SOUND_M_HEAL", PyInt_FromLong((long) 41));
	 PyDict_SetItemString(d,"SOUND_ATK_SPELL", PyInt_FromLong((long) 42));
	 PyDict_SetItemString(d,"SOUND_EVIL", PyInt_FromLong((long) 43));
	 PyDict_SetItemString(d,"SOUND_TOUCH", PyInt_FromLong((long) 44));
	 PyDict_SetItemString(d,"SOUND_STING", PyInt_FromLong((long) 45));
	 PyDict_SetItemString(d,"SOUND_CRUSH", PyInt_FromLong((long) 46));
	 PyDict_SetItemString(d,"SOUND_SLIME", PyInt_FromLong((long) 47));
	 PyDict_SetItemString(d,"SOUND_WAIL", PyInt_FromLong((long) 48));
	 PyDict_SetItemString(d,"SOUND_WINNER", PyInt_FromLong((long) 49));
	 PyDict_SetItemString(d,"SOUND_FIRE", PyInt_FromLong((long) 50));
	 PyDict_SetItemString(d,"SOUND_ACID", PyInt_FromLong((long) 51));
	 PyDict_SetItemString(d,"SOUND_ELEC", PyInt_FromLong((long) 52));
	 PyDict_SetItemString(d,"SOUND_COLD", PyInt_FromLong((long) 53));
	 PyDict_SetItemString(d,"SOUND_ILLEGAL", PyInt_FromLong((long) 54));
	 PyDict_SetItemString(d,"SOUND_FAIL", PyInt_FromLong((long) 55));
	 PyDict_SetItemString(d,"SOUND_WAKEUP", PyInt_FromLong((long) 56));
	 PyDict_SetItemString(d,"SOUND_INVULN", PyInt_FromLong((long) 57));
	 PyDict_SetItemString(d,"SOUND_FALL", PyInt_FromLong((long) 58));
	 PyDict_SetItemString(d,"SOUND_PAIN", PyInt_FromLong((long) 59));
	 PyDict_SetItemString(d,"SOUND_DESTITEM", PyInt_FromLong((long) 60));
	 PyDict_SetItemString(d,"SOUND_MOAN", PyInt_FromLong((long) 61));
	 PyDict_SetItemString(d,"SOUND_SHOW", PyInt_FromLong((long) 62));
	 PyDict_SetItemString(d,"SOUND_UNUSED", PyInt_FromLong((long) 63));
	 PyDict_SetItemString(d,"SOUND_EXPLODE", PyInt_FromLong((long) 64));
	 PyDict_SetItemString(d,"SOUND_MAX", PyInt_FromLong((long) 65));
	 SWIG_addvarlink(SWIG_globals,"option_mask",_wrap_option_mask_get, _wrap_option_mask_set);
	 SWIG_addvarlink(SWIG_globals,"window_flag",_wrap_window_flag_get, _wrap_window_flag_set);
	 SWIG_addvarlink(SWIG_globals,"window_mask",_wrap_window_mask_get, _wrap_window_mask_set);
	 SWIG_addvarlink(SWIG_globals,"angband_term_name",_wrap_angband_term_name_get, _wrap_angband_term_name_set);
	 SWIG_addvarlink(SWIG_globals,"angband_color_table",_wrap_angband_color_table_get, _wrap_angband_color_table_set);
	 SWIG_addvarlink(SWIG_globals,"angband_sound_name",_wrap_angband_sound_name_get, _wrap_angband_sound_name_set);
	 PyDict_SetItemString(d,"PR_MISC", PyInt_FromLong((long) 0x00000001L));
	 PyDict_SetItemString(d,"PR_TITLE", PyInt_FromLong((long) 0x00000002L));
	 PyDict_SetItemString(d,"PR_LEV", PyInt_FromLong((long) 0x00000004L));
	 PyDict_SetItemString(d,"PR_EXP", PyInt_FromLong((long) 0x00000008L));
	 PyDict_SetItemString(d,"PR_STATS", PyInt_FromLong((long) 0x00000010L));
	 PyDict_SetItemString(d,"PR_ARMOR", PyInt_FromLong((long) 0x00000020L));
	 PyDict_SetItemString(d,"PR_HP", PyInt_FromLong((long) 0x00000040L));
	 PyDict_SetItemString(d,"PR_MANA", PyInt_FromLong((long) 0x00000080L));
	 PyDict_SetItemString(d,"PR_GOLD", PyInt_FromLong((long) 0x00000100L));
	 PyDict_SetItemString(d,"PR_DEPTH", PyInt_FromLong((long) 0x00000200L));
	 PyDict_SetItemString(d,"PR_EQUIPPY", PyInt_FromLong((long) 0x00000400L));
	 PyDict_SetItemString(d,"PR_HEALTH", PyInt_FromLong((long) 0x00000800L));
	 PyDict_SetItemString(d,"PR_CUT", PyInt_FromLong((long) 0x00001000L));
	 PyDict_SetItemString(d,"PR_STUN", PyInt_FromLong((long) 0x00002000L));
	 PyDict_SetItemString(d,"PR_HUNGER", PyInt_FromLong((long) 0x00004000L));
	 PyDict_SetItemString(d,"PR_STATUS", PyInt_FromLong((long) 0x00008000L));
	 PyDict_SetItemString(d,"PR_BLIND", PyInt_FromLong((long) 0x00010000L));
	 PyDict_SetItemString(d,"PR_CONFUSED", PyInt_FromLong((long) 0x00020000L));
	 PyDict_SetItemString(d,"PR_AFRAID", PyInt_FromLong((long) 0x00040000L));
	 PyDict_SetItemString(d,"PR_POISONED", PyInt_FromLong((long) 0x00080000L));
	 PyDict_SetItemString(d,"PR_STATE", PyInt_FromLong((long) 0x00100000L));
	 PyDict_SetItemString(d,"PR_SPEED", PyInt_FromLong((long) 0x00200000L));
	 PyDict_SetItemString(d,"PR_STUDY", PyInt_FromLong((long) 0x00400000L));
	 PyDict_SetItemString(d,"PR_EXTRA", PyInt_FromLong((long) 0x01000000L));
	 PyDict_SetItemString(d,"PR_BASIC", PyInt_FromLong((long) 0x02000000L));
	 PyDict_SetItemString(d,"PR_MAP", PyInt_FromLong((long) 0x04000000L));
	 PyDict_SetItemString(d,"PR_WIPE", PyInt_FromLong((long) 0x08000000L));
	 PyDict_SetItemString(d,"PW_INVEN", PyInt_FromLong((long) 0x00000001L));
	 PyDict_SetItemString(d,"PW_EQUIP", PyInt_FromLong((long) 0x00000002L));
	 PyDict_SetItemString(d,"PW_SPELL", PyInt_FromLong((long) 0x00000004L));
	 PyDict_SetItemString(d,"PW_PLAYER", PyInt_FromLong((long) 0x00000008L));
	 PyDict_SetItemString(d,"PW_MESSAGE", PyInt_FromLong((long) 0x00000040L));
	 PyDict_SetItemString(d,"PW_OVERHEAD", PyInt_FromLong((long) 0x00000080L));
	 PyDict_SetItemString(d,"PW_MONSTER", PyInt_FromLong((long) 0x00000100L));
	 PyDict_SetItemString(d,"PW_OBJECT", PyInt_FromLong((long) 0x00000200L));
	 PyDict_SetItemString(d,"PW_DUNGEON", PyInt_FromLong((long) 0x00000400L));
	 PyDict_SetItemString(d,"PW_SNAPSHOT", PyInt_FromLong((long) 0x00000800L));
	 PyDict_SetItemString(d,"PW_SCRIPT", PyInt_FromLong((long) 0x00002000L));
	 PyDict_SetItemString(d,"PW_BORG_1", PyInt_FromLong((long) 0x00004000L));
	 PyDict_SetItemString(d,"PW_BORG_2", PyInt_FromLong((long) 0x00008000L));
	 SWIG_addvarlink(SWIG_globals,"inkey_base",_wrap_inkey_base_get, _wrap_inkey_base_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_xtra",_wrap_inkey_xtra_get, _wrap_inkey_xtra_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_scan",_wrap_inkey_scan_get, _wrap_inkey_scan_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_flag",_wrap_inkey_flag_get, _wrap_inkey_flag_set);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_byte","_unsigned_char",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_cptr","_char_p",0);
	 SWIG_RegisterMapping("_char_p","_cptr",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_s32b",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_s16b","_signed_short",0);
	 SWIG_RegisterMapping("_s16b","_short",0);
	 SWIG_RegisterMapping("_unsigned_short","_u16b",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_s32b","_signed_int",0);
	 SWIG_RegisterMapping("_s32b","_int",0);
	 SWIG_RegisterMapping("_signed_short","_s16b",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_char","_byte",0);
	 SWIG_RegisterMapping("_unsigned_int","_u32b",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_u16b",0);
	 SWIG_RegisterMapping("_short","_s16b",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_u32b",0);
	 SWIG_RegisterMapping("_int","_s32b",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 SWIG_RegisterMapping("_u16b","_unsigned_short",0);
	 SWIG_RegisterMapping("_u16b","_short",0);
	 SWIG_RegisterMapping("_u32b","_unsigned_int",0);
	 SWIG_RegisterMapping("_u32b","_int",0);
}
