/*
 * FILE : .\src\io_wrap.c
 * 
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20000417-1444 (Alpha 2)
 * 
 * Portions Copyright (c) 1995-1999
 * The University of Utah, The Regents of the University of California, and
 * The University of Chicago.  Permission is granted to use and distribute this
 * file in any manner provided this notice remains intact.
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGSTATICRUNTIME(a) static a
#endif

/* Type information structure */

typedef struct _swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  struct _swig_type_info  *next;
  struct _swig_type_info  *prev;
} _swig_type_info;

/* Constant information structure */
typedef struct _swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    _swig_type_info **ptype;
} _swig_const_info;

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(_swig_type_info *) SWIG_TypeRegister(_swig_type_info *);
SWIGEXPORT(_swig_type_info *) SWIG_TypeCheck(char *, _swig_type_info *);
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, _swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, _swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, _swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, _swig_const_info constants[]);

/* External declarations when using runtime libraries */

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

static _swig_type_info *swig_types = 0;

/* Register type mappings with the type-checker */
SWIGSTATICRUNTIME(_swig_type_info *)
SWIG_TypeRegister(_swig_type_info *ti) {
  _swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_types;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_types;
  swig_types = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGSTATICRUNTIME(_swig_type_info *) 
SWIG_TypeCheck(char *c, _swig_type_info *ty) {
  _swig_type_info *s;
  char *sn;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element is always just the name */
  while (s) {
    sn = s->name;
    if ((c == sn) || ((*c == *sn) && (strcmp(sn,c) == 0))) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Convert a pointer value */
SWIGSTATICRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, _swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  _swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    if ((!obj) || !(PyCObject_Check(obj))) goto type_error;
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    if ((!obj) || !(PyString_Check(obj))) goto type_error;
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return 0;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    if (tc->converter) {
      *ptr = (*tc->converter)((void *) p);
    }
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, _swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGSTATICRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, _swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGSTATICRUNTIME(void)
SWIG_InstallConstants(PyObject *d, _swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif


/* ---- TYPES TABLE (BEGIN) ---- */
#define  SWIGTYPE_huge_p _swig_types[0] 
#define  SWIGTYPE_term_p _swig_types[1] 
#define  SWIGTYPE_FILE_p _swig_types[2] 
#define  SWIGTYPE_byte_p _swig_types[3] 
#define  SWIGTYPE_sint_p _swig_types[4] 
#define  SWIGTYPE_errr_p _swig_types[5] 
static _swig_type_info *_swig_types[7];
/* ---- TYPES TABLE (END) ---- */

#define SWIG_init    initioc

#define SWIG_name    "ioc"


#include "angband.h"

char get_line_tmp[1024];

cptr get_line(void)
{
	if (get_string("", get_line_tmp, 1024))
		return get_line_tmp;
	else
		return "\n";

	p_ptr->window |= (PW_SCRIPT);
}

extern const char *get_line();
extern errr path_parse(char *,int ,const char *);
extern errr path_temp(char *,int );
extern errr path_build(char *,int ,const char *,const char *);
extern FILE *my_fopen(const char *,const char *);
extern errr my_fgets(FILE *,char *,huge );
extern errr my_fputs(FILE *,const char *,huge );
extern errr my_fclose(FILE *);
extern errr fd_kill(const char *);
extern errr fd_move(const char *,const char *);
extern errr fd_copy(const char *,const char *);
extern int fd_make(const char *,int );
extern int fd_open(const char *,int );
extern errr fd_lock(int ,int );
extern errr fd_seek(int ,huge );
extern errr fd_chop(int ,huge );
extern errr fd_read(int ,char *,huge );
extern errr fd_write(int ,const char *,huge );
extern errr fd_close(int );
extern void flush();
extern void bell();
extern void sound(int );
extern void move_cursor(int ,int );
extern void text_to_ascii(char *,const char *);
extern void ascii_to_text(char *,const char *);
extern errr macro_add(const char *,const char *);
extern sint macro_find_exact(const char *);
extern char inkey();
extern const char *quark_str(s16b );
extern s16b quark_add(const char *);
extern s16b message_num();
extern const char *message_str(int );
extern void message_add(const char *);
extern void msg_print(const char *);
extern void screen_save();
extern void screen_load();
extern void c_put_str(byte ,const char *,int ,int );
extern void put_str(const char *,int ,int );
extern void c_prt(byte ,const char *,int ,int );
extern void prt(const char *,int ,int );
extern void c_roff(byte ,const char *);
extern void roff(const char *);
extern void clear_from(int );
extern bool askfor_aux(char *,int );
extern bool get_string(const char *,char *,int );
extern bool get_check(const char *);
extern bool get_com(const char *,char *);
extern s16b get_quantity(const char *,int );
extern void pause_line(int );
extern void request_command(int );
extern bool is_a_vowel(int );
extern int get_keymap_dir(char );
extern bool get_aim_dir(int *);
extern term * Term; 
extern errr Term_user(int );
extern errr Term_xtra(int ,int );
extern void Term_queue_chars(int ,int ,int ,byte ,const char *);
extern errr Term_fresh();
extern errr Term_set_cursor(int );
extern errr Term_gotoxy(int ,int );
extern errr Term_draw(int ,int ,byte ,char );
extern errr Term_addch(byte ,char );
extern errr Term_addstr(int ,byte ,const char *);
extern errr Term_putch(int ,int ,byte ,char );
extern errr Term_putstr(int ,int ,int ,byte ,const char *);
extern errr Term_erase(int ,int ,int );
extern errr Term_clear();
extern errr Term_redraw();
extern errr Term_get_cursor(int *);
extern errr Term_get_size(int *,int *);
extern errr Term_locate(int *,int *);
extern errr Term_what(int ,int ,byte *,char *);
extern errr Term_flush();
extern errr Term_keypress(int );
extern errr Term_key_push(int );
extern errr Term_inkey(char *,bool ,bool );
extern errr Term_save();
extern errr Term_load();
extern errr Term_exchange();
extern errr Term_resize(int ,int );
extern errr Term_activate(term *);
extern errr term_nuke(term *);
extern errr term_init(term *,int ,int ,int );
extern u32b  option_flag[8]; 
extern u32b  option_mask[8]; 
extern u32b  window_flag[8]; 
extern u32b  window_mask[8]; 
extern term * angband_term[8]; 
extern char  angband_term_name[8][16]; 
extern byte  angband_color_table[256][4]; 
extern char  angband_sound_name[65][16]; 
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_get_line(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_result;
    self = self;
    if(!PyArg_ParseTuple(args,":get_line")) 
        return NULL;
    _result = (char *)get_line();
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_path_parse(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg1;
    PyObject  *_resultobj;
    char  *_arg0,*_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"sis:path_parse",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = path_parse(_arg0,_arg1,_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_path_temp(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg1;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"si:path_temp",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = path_temp(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_path_build(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg1;
    PyObject  *_resultobj;
    char  *_arg0,*_arg2,*_arg3;
    self = self;
    if(!PyArg_ParseTuple(args,"siss:path_build",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = path_build(_arg0,_arg1,_arg2,_arg3);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_my_fopen(PyObject *self, PyObject *args) {
    FILE  *_result;
    PyObject  *_resultobj;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:my_fopen",&_arg0,&_arg1)) 
        return NULL;
    _result = (FILE *)my_fopen(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *) _result, SWIGTYPE_FILE_p);
    return _resultobj;
}

static PyObject *_wrap_my_fgets(PyObject *self, PyObject *args) {
    FILE  *_arg0;
    errr  *_result;
    PyObject  *_resultobj,*_argo0=0,*_argo2=0;
    char  *_arg1;
    huge  *_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"OsO:my_fgets",&_argo0,&_arg1,&_argo2)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_FILE_p,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(_argo2,(void **) &_arg2,SWIGTYPE_huge_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = my_fgets(_arg0,_arg1,*_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_my_fputs(PyObject *self, PyObject *args) {
    FILE  *_arg0;
    errr  *_result;
    PyObject  *_resultobj,*_argo0=0,*_argo2=0;
    char  *_arg1;
    huge  *_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"OsO:my_fputs",&_argo0,&_arg1,&_argo2)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_FILE_p,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(_argo2,(void **) &_arg2,SWIGTYPE_huge_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = my_fputs(_arg0,_arg1,*_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_my_fclose(PyObject *self, PyObject *args) {
    FILE  *_arg0;
    errr  *_result;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:my_fclose",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_FILE_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = my_fclose(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_kill(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:fd_kill",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_kill(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_move(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:fd_move",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_move(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_copy(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:fd_copy",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_copy(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_make(PyObject *self, PyObject *args) {
    int  _result,_arg1;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"si:fd_make",&_arg0,&_arg1)) 
        return NULL;
    _result = (int )fd_make(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fd_open(PyObject *self, PyObject *args) {
    int  _result,_arg1;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"si:fd_open",&_arg0,&_arg1)) 
        return NULL;
    _result = (int )fd_open(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_fd_lock(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:fd_lock",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_lock(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_seek(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj,*_argo1=0;
    huge  *_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"iO:fd_seek",&_arg0,&_argo1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo1,(void **) &_arg1,SWIGTYPE_huge_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_seek(_arg0,*_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_chop(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj,*_argo1=0;
    huge  *_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"iO:fd_chop",&_arg0,&_argo1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo1,(void **) &_arg1,SWIGTYPE_huge_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_chop(_arg0,*_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_read(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj,*_argo2=0;
    char  *_arg1;
    huge  *_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"isO:fd_read",&_arg0,&_arg1,&_argo2)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo2,(void **) &_arg2,SWIGTYPE_huge_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_read(_arg0,_arg1,*_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_write(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj,*_argo2=0;
    char  *_arg1;
    huge  *_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"isO:fd_write",&_arg0,&_arg1,&_argo2)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo2,(void **) &_arg2,SWIGTYPE_huge_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_write(_arg0,_arg1,*_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_fd_close(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:fd_close",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = fd_close(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_flush(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":flush")) 
        return NULL;
    flush();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_bell(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":bell")) 
        return NULL;
    bell();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_sound(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:sound",&_arg0)) 
        return NULL;
    sound(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_move_cursor(PyObject *self, PyObject *args) {
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:move_cursor",&_arg0,&_arg1)) 
        return NULL;
    move_cursor(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_text_to_ascii(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:text_to_ascii",&_arg0,&_arg1)) 
        return NULL;
    text_to_ascii(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_ascii_to_text(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:ascii_to_text",&_arg0,&_arg1)) 
        return NULL;
    ascii_to_text(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_macro_add(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:macro_add",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = macro_add(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_macro_find_exact(PyObject *self, PyObject *args) {
    sint  *_result;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:macro_find_exact",&_arg0)) 
        return NULL;
    _result = (sint *) malloc(sizeof(sint ));
    *(_result) = macro_find_exact(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_sint_p);
    return _resultobj;
}

static PyObject *_wrap_inkey(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":inkey")) 
        return NULL;
    _result = (char )inkey();
    _resultobj = Py_BuildValue("c",_result);
    return _resultobj;
}

static PyObject *_wrap_quark_str(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    s16b  _arg0;
    char  *_result;
    self = self;
    if(!PyArg_ParseTuple(args,"h:quark_str",&_arg0)) 
        return NULL;
    _result = (char *)quark_str(_arg0);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_quark_add(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    s16b  _result;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:quark_add",&_arg0)) 
        return NULL;
    _result = (s16b )quark_add(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_message_num(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,":message_num")) 
        return NULL;
    _result = (s16b )message_num();
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_message_str(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    char  *_result;
    self = self;
    if(!PyArg_ParseTuple(args,"i:message_str",&_arg0)) 
        return NULL;
    _result = (char *)message_str(_arg0);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static PyObject *_wrap_message_add(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:message_add",&_arg0)) 
        return NULL;
    message_add(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_msg_print(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:msg_print",&_arg0)) 
        return NULL;
    msg_print(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_screen_save(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":screen_save")) 
        return NULL;
    screen_save();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_screen_load(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":screen_load")) 
        return NULL;
    screen_load();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_c_put_str(PyObject *self, PyObject *args) {
    int  _arg2,_arg3;
    PyObject  *_resultobj;
    byte  _arg0;
    char  *_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"bsii:c_put_str",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    c_put_str(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_put_str(PyObject *self, PyObject *args) {
    int  _arg1,_arg2;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"sii:put_str",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    put_str(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_c_prt(PyObject *self, PyObject *args) {
    int  _arg2,_arg3;
    PyObject  *_resultobj;
    byte  _arg0;
    char  *_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"bsii:c_prt",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    c_prt(_arg0,_arg1,_arg2,_arg3);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_prt(PyObject *self, PyObject *args) {
    int  _arg1,_arg2;
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"sii:prt",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    prt(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_c_roff(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    byte  _arg0;
    char  *_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"bs:c_roff",&_arg0,&_arg1)) 
        return NULL;
    c_roff(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_roff(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:roff",&_arg0)) 
        return NULL;
    roff(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_clear_from(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:clear_from",&_arg0)) 
        return NULL;
    clear_from(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_askfor_aux(PyObject *self, PyObject *args) {
    int  _arg1;
    PyObject  *_resultobj;
    bool  _result;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"si:askfor_aux",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )askfor_aux(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_string(PyObject *self, PyObject *args) {
    int  _arg2;
    PyObject  *_resultobj;
    bool  _result;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ssi:get_string",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (bool )get_string(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_check(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"s:get_check",&_arg0)) 
        return NULL;
    _result = (bool )get_check(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_com(PyObject *self, PyObject *args) {
    PyObject  *_resultobj;
    bool  _result;
    char  *_arg0,*_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"ss:get_com",&_arg0,&_arg1)) 
        return NULL;
    _result = (bool )get_com(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_quantity(PyObject *self, PyObject *args) {
    int  _arg1;
    PyObject  *_resultobj;
    s16b  _result;
    char  *_arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"si:get_quantity",&_arg0,&_arg1)) 
        return NULL;
    _result = (s16b )get_quantity(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_pause_line(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:pause_line",&_arg0)) 
        return NULL;
    pause_line(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_request_command(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:request_command",&_arg0)) 
        return NULL;
    request_command(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_is_a_vowel(PyObject *self, PyObject *args) {
    int  _arg0;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"i:is_a_vowel",&_arg0)) 
        return NULL;
    _result = (bool )is_a_vowel(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_keymap_dir(PyObject *self, PyObject *args) {
    int  _result;
    PyObject  *_resultobj;
    char  _arg0;
    self = self;
    if(!PyArg_ParseTuple(args,"c:get_keymap_dir",&_arg0)) 
        return NULL;
    _result = (int )get_keymap_dir(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_get_aim_dir(PyObject *self, PyObject *args) {
    int  temp;
    int  *_arg0;
    PyObject  *_resultobj;
    bool  _result;
    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":get_aim_dir")) 
        return NULL;
    _result = (bool )get_aim_dir(_arg0);
    _resultobj = Py_BuildValue("i",_result);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static int _wrap_Term_set(PyObject *val) {
    term  *temp;
    if ((SWIG_ConvertPtr(val,(void **) &temp,SWIGTYPE_term_p,1)) == -1) return 1;
    Term = temp;
    return 0;
}

static PyObject *_wrap_Term_get() {
    PyObject  *pyobj;
    pyobj = SWIG_NewPointerObj((void *)Term, SWIGTYPE_term_p);
    return pyobj;
}

static PyObject *_wrap_Term_user(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_user",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_user(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_xtra(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:Term_xtra",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_xtra(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_queue_chars(PyObject *self, PyObject *args) {
    int  _arg0,_arg1,_arg2;
    PyObject  *_resultobj;
    byte  _arg3;
    char  *_arg4;
    self = self;
    if(!PyArg_ParseTuple(args,"iiibs:Term_queue_chars",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    Term_queue_chars(_arg0,_arg1,_arg2,_arg3,_arg4);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Term_fresh(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_fresh")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_fresh();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_set_cursor(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_set_cursor",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_set_cursor(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_gotoxy(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:Term_gotoxy",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_gotoxy(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_draw(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    byte  _arg2;
    char  _arg3;
    self = self;
    if(!PyArg_ParseTuple(args,"iibc:Term_draw",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_draw(_arg0,_arg1,_arg2,_arg3);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_addch(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    byte  _arg0;
    char  _arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"bc:Term_addch",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_addch(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_addstr(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj;
    byte  _arg1;
    char  *_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"ibs:Term_addstr",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_addstr(_arg0,_arg1,_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_putch(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    byte  _arg2;
    char  _arg3;
    self = self;
    if(!PyArg_ParseTuple(args,"iibc:Term_putch",&_arg0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_putch(_arg0,_arg1,_arg2,_arg3);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_putstr(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1,_arg2;
    PyObject  *_resultobj;
    byte  _arg3;
    char  *_arg4;
    self = self;
    if(!PyArg_ParseTuple(args,"iiibs:Term_putstr",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_putstr(_arg0,_arg1,_arg2,_arg3,_arg4);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_erase(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1,_arg2;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"iii:Term_erase",&_arg0,&_arg1,&_arg2)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_erase(_arg0,_arg1,_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_clear(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_clear")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_clear();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_redraw(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_redraw")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_redraw();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_get_cursor(PyObject *self, PyObject *args) {
    int  temp;
    errr  *_result;
    int  *_arg0;
    PyObject  *_resultobj;
    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":Term_get_cursor")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_get_cursor(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static PyObject *_wrap_Term_get_size(PyObject *self, PyObject *args) {
    int  temp;
    int  temp0;
    errr  *_result;
    int  *_arg0,*_arg1;
    PyObject  *_resultobj;
    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
{
	_arg1 = &temp0; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":Term_get_size")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_get_size(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
{
	PyObject *o;

	o = PyInt_FromLong(*_arg1);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static PyObject *_wrap_Term_locate(PyObject *self, PyObject *args) {
    int  temp;
    int  temp0;
    errr  *_result;
    int  *_arg0,*_arg1;
    PyObject  *_resultobj;
    self = self;
{
	_arg0 = &temp; /* Assign the pointer to a local variable */
}
{
	_arg1 = &temp0; /* Assign the pointer to a local variable */
}
    if(!PyArg_ParseTuple(args,":Term_locate")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_locate(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
{
	PyObject *o;

	o = PyInt_FromLong(*_arg0);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
{
	PyObject *o;

	o = PyInt_FromLong(*_arg1);

	if ((!_resultobj) || (_resultobj == Py_None))
	{
		_resultobj = o;
	}
	else
	{
		if (!PyList_Check(_resultobj))
		{
			PyObject *o2 = _resultobj;
			_resultobj = PyList_New(0);
			PyList_Append(_resultobj, o2);
			Py_XDECREF(o2);
		}

		PyList_Append(_resultobj, o);
		Py_XDECREF(o);
	}
}
    return _resultobj;
}

static PyObject *_wrap_Term_what(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj,*_argo2=0;
    byte  *_arg2;
    char  *_arg3;
    self = self;
    if(!PyArg_ParseTuple(args,"iiOs:Term_what",&_arg0,&_arg1,&_argo2,&_arg3)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo2,(void **) &_arg2,SWIGTYPE_byte_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_what(_arg0,_arg1,_arg2,_arg3);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_flush(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_flush")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_flush();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_keypress(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_keypress",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_keypress(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_key_push(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"i:Term_key_push",&_arg0)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_key_push(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_inkey(PyObject *self, PyObject *args) {
    errr  *_result;
    int tempbool1,tempbool2;
    PyObject  *_resultobj;
    char  *_arg0;
    bool  _arg1,_arg2;
    self = self;
    if(!PyArg_ParseTuple(args,"sii:Term_inkey",&_arg0,&tempbool1,&tempbool2)) 
        return NULL;
    _arg1 = (bool ) tempbool1;
    _arg2 = (bool ) tempbool2;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_inkey(_arg0,_arg1,_arg2);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_save(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_save")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_save();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_load(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_load")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_load();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_exchange(PyObject *self, PyObject *args) {
    errr  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":Term_exchange")) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_exchange();
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_resize(PyObject *self, PyObject *args) {
    errr  *_result;
    int  _arg0,_arg1;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,"ii:Term_resize",&_arg0,&_arg1)) 
        return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_resize(_arg0,_arg1);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_Term_activate(PyObject *self, PyObject *args) {
    term  *_arg0;
    errr  *_result;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:Term_activate",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_term_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = Term_activate(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_term_nuke(PyObject *self, PyObject *args) {
    term  *_arg0;
    errr  *_result;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:term_nuke",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_term_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = term_nuke(_arg0);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static PyObject *_wrap_term_init(PyObject *self, PyObject *args) {
    term  *_arg0;
    errr  *_result;
    int  _arg1,_arg2,_arg3;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"Oiii:term_init",&_argo0,&_arg1,&_arg2,&_arg3)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_term_p,1)) == -1) return NULL;
    _result = (errr *) malloc(sizeof(errr ));
    *(_result) = term_init(_arg0,_arg1,_arg2,_arg3);
    _resultobj = SWIG_NewPointerObj((void *)_result, SWIGTYPE_errr_p);
    return _resultobj;
}

static int _wrap_option_flag_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable option_flag is read-only.");
    return 1;
}

static PyObject *_wrap_option_flag_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(option_flag[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_option_mask_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable option_mask is read-only.");
    return 1;
}

static PyObject *_wrap_option_mask_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(option_mask[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_window_flag_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable window_flag is read-only.");
    return 1;
}

static PyObject *_wrap_window_flag_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(window_flag[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_window_mask_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable window_mask is read-only.");
    return 1;
}

static PyObject *_wrap_window_mask_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyInt_FromLong(window_mask[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_angband_term_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable angband_term is read-only.");
    return 1;
}

static PyObject *_wrap_angband_term_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = SWIG_NewPointerObj((void *)angband_term[i], SWIGTYPE_term_p);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_angband_term_name_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable angband_term_name is read-only.");
    return 1;
}

static PyObject *_wrap_angband_term_name_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(8);

	for (i = 0; i < 8; i++)
	{
		o = PyString_FromString(angband_term_name[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_angband_color_table_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable angband_color_table is read-only.");
    return 1;
}

static PyObject *_wrap_angband_color_table_get() {
    PyObject  *pyobj;
{
	PyObject *tuple;
	int i, j;

	pyobj = PyList_New(256);

	for (i = 0; i < 256; i++)
	{
		tuple = PyTuple_New(4);

		for (j = 0; j < 4; j++)
			PyTuple_SetItem(tuple, j, PyInt_FromLong(angband_color_table[i][j]));

		PyList_SetItem(pyobj, i, tuple);
	}
}
    return pyobj;
}

static int _wrap_angband_sound_name_set(PyObject *val) {
    PyErr_SetString(PyExc_TypeError,"Variable angband_sound_name is read-only.");
    return 1;
}

static PyObject *_wrap_angband_sound_name_get() {
    PyObject  *pyobj;
{
	PyObject *o;
	int i;

	pyobj = PyList_New(65);

	for (i = 0; i < 65; i++)
	{
		o = PyString_FromString(angband_sound_name[i]);
		PyList_SetItem(pyobj, i, o);
	}
}
    return pyobj;
}

static int _wrap_inkey_base_set(PyObject *val) {
    bool  tval;
    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_base'(bool )");
        return 1; 
    }
    inkey_base = tval;
    return 0;
}

static PyObject *_wrap_inkey_base_get() {
    PyObject  *pyobj;
    pyobj = PyInt_FromLong((long) inkey_base);
    return pyobj;
}

static int _wrap_inkey_xtra_set(PyObject *val) {
    bool  tval;
    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_xtra'(bool )");
        return 1; 
    }
    inkey_xtra = tval;
    return 0;
}

static PyObject *_wrap_inkey_xtra_get() {
    PyObject  *pyobj;
    pyobj = PyInt_FromLong((long) inkey_xtra);
    return pyobj;
}

static int _wrap_inkey_scan_set(PyObject *val) {
    bool  tval;
    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_scan'(bool )");
        return 1; 
    }
    inkey_scan = tval;
    return 0;
}

static PyObject *_wrap_inkey_scan_get() {
    PyObject  *pyobj;
    pyobj = PyInt_FromLong((long) inkey_scan);
    return pyobj;
}

static int _wrap_inkey_flag_set(PyObject *val) {
    bool  tval;
    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'inkey_flag'(bool )");
        return 1; 
    }
    inkey_flag = tval;
    return 0;
}

static PyObject *_wrap_inkey_flag_get() {
    PyObject  *pyobj;
    pyobj = PyInt_FromLong((long) inkey_flag);
    return pyobj;
}

static PyMethodDef iocMethods[] = {
	 { "term_init", _wrap_term_init, METH_VARARGS },
	 { "term_nuke", _wrap_term_nuke, METH_VARARGS },
	 { "Term_activate", _wrap_Term_activate, METH_VARARGS },
	 { "Term_resize", _wrap_Term_resize, METH_VARARGS },
	 { "Term_exchange", _wrap_Term_exchange, METH_VARARGS },
	 { "Term_load", _wrap_Term_load, METH_VARARGS },
	 { "Term_save", _wrap_Term_save, METH_VARARGS },
	 { "Term_inkey", _wrap_Term_inkey, METH_VARARGS },
	 { "Term_key_push", _wrap_Term_key_push, METH_VARARGS },
	 { "Term_keypress", _wrap_Term_keypress, METH_VARARGS },
	 { "Term_flush", _wrap_Term_flush, METH_VARARGS },
	 { "Term_what", _wrap_Term_what, METH_VARARGS },
	 { "Term_locate", _wrap_Term_locate, METH_VARARGS },
	 { "Term_get_size", _wrap_Term_get_size, METH_VARARGS },
	 { "Term_get_cursor", _wrap_Term_get_cursor, METH_VARARGS },
	 { "Term_redraw", _wrap_Term_redraw, METH_VARARGS },
	 { "Term_clear", _wrap_Term_clear, METH_VARARGS },
	 { "Term_erase", _wrap_Term_erase, METH_VARARGS },
	 { "Term_putstr", _wrap_Term_putstr, METH_VARARGS },
	 { "Term_putch", _wrap_Term_putch, METH_VARARGS },
	 { "Term_addstr", _wrap_Term_addstr, METH_VARARGS },
	 { "Term_addch", _wrap_Term_addch, METH_VARARGS },
	 { "Term_draw", _wrap_Term_draw, METH_VARARGS },
	 { "Term_gotoxy", _wrap_Term_gotoxy, METH_VARARGS },
	 { "Term_set_cursor", _wrap_Term_set_cursor, METH_VARARGS },
	 { "Term_fresh", _wrap_Term_fresh, METH_VARARGS },
	 { "Term_queue_chars", _wrap_Term_queue_chars, METH_VARARGS },
	 { "Term_xtra", _wrap_Term_xtra, METH_VARARGS },
	 { "Term_user", _wrap_Term_user, METH_VARARGS },
	 { "get_aim_dir", _wrap_get_aim_dir, METH_VARARGS },
	 { "get_keymap_dir", _wrap_get_keymap_dir, METH_VARARGS },
	 { "is_a_vowel", _wrap_is_a_vowel, METH_VARARGS },
	 { "request_command", _wrap_request_command, METH_VARARGS },
	 { "pause_line", _wrap_pause_line, METH_VARARGS },
	 { "get_quantity", _wrap_get_quantity, METH_VARARGS },
	 { "get_com", _wrap_get_com, METH_VARARGS },
	 { "get_check", _wrap_get_check, METH_VARARGS },
	 { "get_string", _wrap_get_string, METH_VARARGS },
	 { "askfor_aux", _wrap_askfor_aux, METH_VARARGS },
	 { "clear_from", _wrap_clear_from, METH_VARARGS },
	 { "roff", _wrap_roff, METH_VARARGS },
	 { "c_roff", _wrap_c_roff, METH_VARARGS },
	 { "prt", _wrap_prt, METH_VARARGS },
	 { "c_prt", _wrap_c_prt, METH_VARARGS },
	 { "put_str", _wrap_put_str, METH_VARARGS },
	 { "c_put_str", _wrap_c_put_str, METH_VARARGS },
	 { "screen_load", _wrap_screen_load, METH_VARARGS },
	 { "screen_save", _wrap_screen_save, METH_VARARGS },
	 { "msg_print", _wrap_msg_print, METH_VARARGS },
	 { "message_add", _wrap_message_add, METH_VARARGS },
	 { "message_str", _wrap_message_str, METH_VARARGS },
	 { "message_num", _wrap_message_num, METH_VARARGS },
	 { "quark_add", _wrap_quark_add, METH_VARARGS },
	 { "quark_str", _wrap_quark_str, METH_VARARGS },
	 { "inkey", _wrap_inkey, METH_VARARGS },
	 { "macro_find_exact", _wrap_macro_find_exact, METH_VARARGS },
	 { "macro_add", _wrap_macro_add, METH_VARARGS },
	 { "ascii_to_text", _wrap_ascii_to_text, METH_VARARGS },
	 { "text_to_ascii", _wrap_text_to_ascii, METH_VARARGS },
	 { "move_cursor", _wrap_move_cursor, METH_VARARGS },
	 { "sound", _wrap_sound, METH_VARARGS },
	 { "bell", _wrap_bell, METH_VARARGS },
	 { "flush", _wrap_flush, METH_VARARGS },
	 { "fd_close", _wrap_fd_close, METH_VARARGS },
	 { "fd_write", _wrap_fd_write, METH_VARARGS },
	 { "fd_read", _wrap_fd_read, METH_VARARGS },
	 { "fd_chop", _wrap_fd_chop, METH_VARARGS },
	 { "fd_seek", _wrap_fd_seek, METH_VARARGS },
	 { "fd_lock", _wrap_fd_lock, METH_VARARGS },
	 { "fd_open", _wrap_fd_open, METH_VARARGS },
	 { "fd_make", _wrap_fd_make, METH_VARARGS },
	 { "fd_copy", _wrap_fd_copy, METH_VARARGS },
	 { "fd_move", _wrap_fd_move, METH_VARARGS },
	 { "fd_kill", _wrap_fd_kill, METH_VARARGS },
	 { "my_fclose", _wrap_my_fclose, METH_VARARGS },
	 { "my_fputs", _wrap_my_fputs, METH_VARARGS },
	 { "my_fgets", _wrap_my_fgets, METH_VARARGS },
	 { "my_fopen", _wrap_my_fopen, METH_VARARGS },
	 { "path_build", _wrap_path_build, METH_VARARGS },
	 { "path_temp", _wrap_path_temp, METH_VARARGS },
	 { "path_parse", _wrap_path_parse, METH_VARARGS },
	 { "get_line", _wrap_get_line, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
static _swig_type_info _swigt__huge_p[] = {{"_huge_p",0},{"_huge_p",0},{0}};
static _swig_type_info _swigt__term_p[] = {{"_term_p",0},{"_term_p",0},{0}};
static _swig_type_info _swigt__FILE_p[] = {{"_FILE_p",0},{"_FILE_p",0},{0}};
static _swig_type_info _swigt__byte_p[] = {{"_byte_p",0},{"_byte_p",0},{ "_unsigned_char_p",0}, {0}};
static _swig_type_info _swigt__sint_p[] = {{"_sint_p",0},{"_sint_p",0},{0}};
static _swig_type_info _swigt__errr_p[] = {{"_errr_p",0},{"_errr_p",0},{0}};

static _swig_type_info *_swig_types_initial[] = {
_swigt__huge_p, 
_swigt__term_p, 
_swigt__FILE_p, 
_swigt__byte_p, 
_swigt__sint_p, 
_swigt__errr_p, 
0
};

static _swig_const_info _swig_const_table[] = {
    { SWIG_PY_INT,     "TERM_XTRA_EVENT", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_FLUSH", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_CLEAR", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_SHAPE", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_FROSH", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_FRESH", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_NOISE", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_SOUND", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_BORED", (long) 9, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_REACT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_ALIVE", (long) 11, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_LEVEL", (long) 12, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_XTRA_DELAY", (long) 13, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_DARK", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_WHITE", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_SLATE", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_ORANGE", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_RED", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_GREEN", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_BLUE", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_UMBER", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_L_DARK", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_L_WHITE", (long) 9, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_VIOLET", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_YELLOW", (long) 11, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_L_RED", (long) 12, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_L_GREEN", (long) 13, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_L_BLUE", (long) 14, 0, 0, 0},
    { SWIG_PY_INT,     "TERM_L_UMBER", (long) 15, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_HIT", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_MISS", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_FLEE", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_DROP", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_KILL", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_LEVEL", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_DEATH", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_STUDY", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_TELEPORT", (long) 9, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SHOOT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_QUAFF", (long) 11, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_ZAP", (long) 12, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_WALK", (long) 13, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_TPOTHER", (long) 14, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_HITWALL", (long) 15, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_EAT", (long) 16, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_STORE1", (long) 17, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_STORE2", (long) 18, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_STORE3", (long) 19, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_STORE4", (long) 20, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_DIG", (long) 21, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_OPENDOOR", (long) 22, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SHUTDOOR", (long) 23, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_TPLEVEL", (long) 24, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SCROLL", (long) 25, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_BUY", (long) 26, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SELL", (long) 27, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_WARN", (long) 28, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_ROCKET", (long) 29, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_N_KILL", (long) 30, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_U_KILL", (long) 31, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_QUEST", (long) 32, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_HEAL", (long) 33, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_X_HEAL", (long) 34, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_BITE", (long) 35, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_CLAW", (long) 36, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_M_SPELL", (long) 37, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SUMMON", (long) 38, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_BREATH", (long) 39, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_BALL", (long) 40, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_M_HEAL", (long) 41, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_ATK_SPELL", (long) 42, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_EVIL", (long) 43, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_TOUCH", (long) 44, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_STING", (long) 45, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_CRUSH", (long) 46, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SLIME", (long) 47, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_WAIL", (long) 48, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_WINNER", (long) 49, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_FIRE", (long) 50, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_ACID", (long) 51, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_ELEC", (long) 52, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_COLD", (long) 53, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_ILLEGAL", (long) 54, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_FAIL", (long) 55, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_WAKEUP", (long) 56, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_INVULN", (long) 57, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_FALL", (long) 58, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_PAIN", (long) 59, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_DESTITEM", (long) 60, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_MOAN", (long) 61, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_SHOW", (long) 62, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_UNUSED", (long) 63, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_EXPLODE", (long) 64, 0, 0, 0},
    { SWIG_PY_INT,     "SOUND_MAX", (long) 65, 0, 0, 0},
    { SWIG_PY_INT,     "PR_MISC", (long) 0x00000001L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_TITLE", (long) 0x00000002L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_LEV", (long) 0x00000004L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_EXP", (long) 0x00000008L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_STATS", (long) 0x00000010L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_ARMOR", (long) 0x00000020L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_HP", (long) 0x00000040L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_MANA", (long) 0x00000080L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_GOLD", (long) 0x00000100L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_DEPTH", (long) 0x00000200L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_EQUIPPY", (long) 0x00000400L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_HEALTH", (long) 0x00000800L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_CUT", (long) 0x00001000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_STUN", (long) 0x00002000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_HUNGER", (long) 0x00004000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_STATUS", (long) 0x00008000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_BLIND", (long) 0x00010000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_CONFUSED", (long) 0x00020000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_AFRAID", (long) 0x00040000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_POISONED", (long) 0x00080000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_STATE", (long) 0x00100000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_SPEED", (long) 0x00200000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_STUDY", (long) 0x00400000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_EXTRA", (long) 0x01000000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_BASIC", (long) 0x02000000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_MAP", (long) 0x04000000L, 0, 0, 0},
    { SWIG_PY_INT,     "PR_WIPE", (long) 0x08000000L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_INVEN", (long) 0x00000001L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_EQUIP", (long) 0x00000002L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_SPELL", (long) 0x00000004L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_PLAYER", (long) 0x00000008L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_MESSAGE", (long) 0x00000040L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_OVERHEAD", (long) 0x00000080L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_MONSTER", (long) 0x00000100L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_OBJECT", (long) 0x00000200L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_DUNGEON", (long) 0x00000400L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_SNAPSHOT", (long) 0x00000800L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_SCRIPT", (long) 0x00002000L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_BORG_1", (long) 0x00004000L, 0, 0, 0},
    { SWIG_PY_INT,     "PW_BORG_2", (long) 0x00008000L, 0, 0, 0},
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initioc(void) {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("ioc", iocMethods);
	 d = PyModule_GetDict(m);
    {
        int i;
        for (i = 0; _swig_types_initial[i]; i++) {
            _swig_types[i] = SWIG_TypeRegister(_swig_types_initial[i]);
        }
    }
	 PyDict_SetItemString(d,"cvar", SWIG_globals);
	 SWIG_addvarlink(SWIG_globals,"Term",_wrap_Term_get, _wrap_Term_set);
	 SWIG_addvarlink(SWIG_globals,"option_flag",_wrap_option_flag_get, _wrap_option_flag_set);
	 SWIG_addvarlink(SWIG_globals,"option_mask",_wrap_option_mask_get, _wrap_option_mask_set);
	 SWIG_addvarlink(SWIG_globals,"window_flag",_wrap_window_flag_get, _wrap_window_flag_set);
	 SWIG_addvarlink(SWIG_globals,"window_mask",_wrap_window_mask_get, _wrap_window_mask_set);
	 SWIG_addvarlink(SWIG_globals,"angband_term",_wrap_angband_term_get, _wrap_angband_term_set);
	 SWIG_addvarlink(SWIG_globals,"angband_term_name",_wrap_angband_term_name_get, _wrap_angband_term_name_set);
	 SWIG_addvarlink(SWIG_globals,"angband_color_table",_wrap_angband_color_table_get, _wrap_angband_color_table_set);
	 SWIG_addvarlink(SWIG_globals,"angband_sound_name",_wrap_angband_sound_name_get, _wrap_angband_sound_name_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_base",_wrap_inkey_base_get, _wrap_inkey_base_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_xtra",_wrap_inkey_xtra_get, _wrap_inkey_xtra_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_scan",_wrap_inkey_scan_get, _wrap_inkey_scan_set);
	 SWIG_addvarlink(SWIG_globals,"inkey_flag",_wrap_inkey_flag_get, _wrap_inkey_flag_set);
    SWIG_InstallConstants(d,_swig_const_table);

}
