/*
 * FILE : .\src\pclass_wrap.c
 * 
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20000417-1444 (Alpha 2)
 * 
 * Portions Copyright (c) 1995-1999
 * The University of Utah, The Regents of the University of California, and
 * The University of Chicago.  Permission is granted to use and distribute this
 * file in any manner provided this notice remains intact.
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGSTATICRUNTIME(a) static a
#endif

/* Type information structure */

typedef struct _swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  struct _swig_type_info  *next;
  struct _swig_type_info  *prev;
} _swig_type_info;

/* Constant information structure */
typedef struct _swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    _swig_type_info **ptype;
} _swig_const_info;

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(_swig_type_info *) SWIG_TypeRegister(_swig_type_info *);
SWIGEXPORT(_swig_type_info *) SWIG_TypeCheck(char *, _swig_type_info *);
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, _swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, _swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, _swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, _swig_const_info constants[]);

/* External declarations when using runtime libraries */

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

static _swig_type_info *swig_types = 0;

/* Register type mappings with the type-checker */
SWIGSTATICRUNTIME(_swig_type_info *)
SWIG_TypeRegister(_swig_type_info *ti) {
  _swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_types;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_types;
  swig_types = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGSTATICRUNTIME(_swig_type_info *) 
SWIG_TypeCheck(char *c, _swig_type_info *ty) {
  _swig_type_info *s;
  char *sn;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element is always just the name */
  while (s) {
    sn = s->name;
    if ((c == sn) || ((*c == *sn) && (strcmp(sn,c) == 0))) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Convert a pointer value */
SWIGSTATICRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, _swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  _swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    if ((!obj) || !(PyCObject_Check(obj))) goto type_error;
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    if ((!obj) || !(PyString_Check(obj))) goto type_error;
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return 0;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    if (tc->converter) {
      *ptr = (*tc->converter)((void *) p);
    }
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, _swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGSTATICRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, _swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGSTATICRUNTIME(void)
SWIG_InstallConstants(PyObject *d, _swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif


/* ---- TYPES TABLE (BEGIN) ---- */
#define  SWIGTYPE_player_class_p _swig_types[0] 
#define  SWIGTYPE_s16b_p _swig_types[1] 
static _swig_type_info *_swig_types[3];
/* ---- TYPES TABLE (END) ---- */

#define SWIG_init    initpclassc

#define SWIG_name    "pclassc"


#include "angband.h"

#ifdef __cplusplus
extern "C" {
#endif
static cptr  player_class_title_set(struct player_class *obj, cptr val) {
{
	obj->title = string_make(val);
}
    return (cptr ) val;
}
static PyObject *_wrap_player_class_title_set(PyObject *self, PyObject *args) {
    cptr  _result,_arg1;
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"Os:player_class_title_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (cptr )player_class_title_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static cptr  player_class_title_get(struct player_class *obj) {
    cptr  result;
{
	result = obj->title;
}
    return result;
}
static PyObject *_wrap_player_class_title_get(PyObject *self, PyObject *args) {
    cptr  _result;
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_title_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (cptr )player_class_title_get(_arg0);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

#define player_class_c_adj_get(_swigobj) ((s16b *) _swigobj->c_adj)
static PyObject *_wrap_player_class_c_adj_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  *_result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_adj_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b *)player_class_c_adj_get(_arg0);
    _resultobj = SWIG_NewPointerObj((void *) _result, SWIGTYPE_s16b_p);
    return _resultobj;
}

#define player_class_c_dis_set(_swigobj,_swigval) (_swigobj->c_dis = _swigval,_swigval)
static PyObject *_wrap_player_class_c_dis_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_dis_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_dis_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_dis_get(_swigobj) ((s16b ) _swigobj->c_dis)
static PyObject *_wrap_player_class_c_dis_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_dis_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_dis_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_dev_set(_swigobj,_swigval) (_swigobj->c_dev = _swigval,_swigval)
static PyObject *_wrap_player_class_c_dev_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_dev_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_dev_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_dev_get(_swigobj) ((s16b ) _swigobj->c_dev)
static PyObject *_wrap_player_class_c_dev_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_dev_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_dev_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_sav_set(_swigobj,_swigval) (_swigobj->c_sav = _swigval,_swigval)
static PyObject *_wrap_player_class_c_sav_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_sav_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_sav_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_sav_get(_swigobj) ((s16b ) _swigobj->c_sav)
static PyObject *_wrap_player_class_c_sav_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_sav_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_sav_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_stl_set(_swigobj,_swigval) (_swigobj->c_stl = _swigval,_swigval)
static PyObject *_wrap_player_class_c_stl_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_stl_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_stl_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_stl_get(_swigobj) ((s16b ) _swigobj->c_stl)
static PyObject *_wrap_player_class_c_stl_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_stl_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_stl_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_srh_set(_swigobj,_swigval) (_swigobj->c_srh = _swigval,_swigval)
static PyObject *_wrap_player_class_c_srh_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_srh_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_srh_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_srh_get(_swigobj) ((s16b ) _swigobj->c_srh)
static PyObject *_wrap_player_class_c_srh_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_srh_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_srh_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_fos_set(_swigobj,_swigval) (_swigobj->c_fos = _swigval,_swigval)
static PyObject *_wrap_player_class_c_fos_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_fos_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_fos_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_fos_get(_swigobj) ((s16b ) _swigobj->c_fos)
static PyObject *_wrap_player_class_c_fos_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_fos_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_fos_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_thn_set(_swigobj,_swigval) (_swigobj->c_thn = _swigval,_swigval)
static PyObject *_wrap_player_class_c_thn_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_thn_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_thn_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_thn_get(_swigobj) ((s16b ) _swigobj->c_thn)
static PyObject *_wrap_player_class_c_thn_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_thn_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_thn_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_thb_set(_swigobj,_swigval) (_swigobj->c_thb = _swigval,_swigval)
static PyObject *_wrap_player_class_c_thb_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_thb_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_thb_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_thb_get(_swigobj) ((s16b ) _swigobj->c_thb)
static PyObject *_wrap_player_class_c_thb_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_thb_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_thb_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_dis_set(_swigobj,_swigval) (_swigobj->x_dis = _swigval,_swigval)
static PyObject *_wrap_player_class_x_dis_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_dis_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_dis_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_dis_get(_swigobj) ((s16b ) _swigobj->x_dis)
static PyObject *_wrap_player_class_x_dis_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_dis_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_dis_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_dev_set(_swigobj,_swigval) (_swigobj->x_dev = _swigval,_swigval)
static PyObject *_wrap_player_class_x_dev_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_dev_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_dev_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_dev_get(_swigobj) ((s16b ) _swigobj->x_dev)
static PyObject *_wrap_player_class_x_dev_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_dev_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_dev_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_sav_set(_swigobj,_swigval) (_swigobj->x_sav = _swigval,_swigval)
static PyObject *_wrap_player_class_x_sav_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_sav_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_sav_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_sav_get(_swigobj) ((s16b ) _swigobj->x_sav)
static PyObject *_wrap_player_class_x_sav_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_sav_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_sav_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_stl_set(_swigobj,_swigval) (_swigobj->x_stl = _swigval,_swigval)
static PyObject *_wrap_player_class_x_stl_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_stl_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_stl_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_stl_get(_swigobj) ((s16b ) _swigobj->x_stl)
static PyObject *_wrap_player_class_x_stl_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_stl_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_stl_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_srh_set(_swigobj,_swigval) (_swigobj->x_srh = _swigval,_swigval)
static PyObject *_wrap_player_class_x_srh_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_srh_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_srh_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_srh_get(_swigobj) ((s16b ) _swigobj->x_srh)
static PyObject *_wrap_player_class_x_srh_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_srh_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_srh_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_fos_set(_swigobj,_swigval) (_swigobj->x_fos = _swigval,_swigval)
static PyObject *_wrap_player_class_x_fos_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_fos_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_fos_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_fos_get(_swigobj) ((s16b ) _swigobj->x_fos)
static PyObject *_wrap_player_class_x_fos_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_fos_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_fos_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_thn_set(_swigobj,_swigval) (_swigobj->x_thn = _swigval,_swigval)
static PyObject *_wrap_player_class_x_thn_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_thn_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_thn_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_thn_get(_swigobj) ((s16b ) _swigobj->x_thn)
static PyObject *_wrap_player_class_x_thn_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_thn_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_thn_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_thb_set(_swigobj,_swigval) (_swigobj->x_thb = _swigval,_swigval)
static PyObject *_wrap_player_class_x_thb_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_x_thb_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_thb_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_x_thb_get(_swigobj) ((s16b ) _swigobj->x_thb)
static PyObject *_wrap_player_class_x_thb_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_x_thb_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_x_thb_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_mhp_set(_swigobj,_swigval) (_swigobj->c_mhp = _swigval,_swigval)
static PyObject *_wrap_player_class_c_mhp_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_mhp_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_mhp_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_mhp_get(_swigobj) ((s16b ) _swigobj->c_mhp)
static PyObject *_wrap_player_class_c_mhp_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_mhp_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_mhp_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_exp_set(_swigobj,_swigval) (_swigobj->c_exp = _swigval,_swigval)
static PyObject *_wrap_player_class_c_exp_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_c_exp_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_exp_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_c_exp_get(_swigobj) ((s16b ) _swigobj->c_exp)
static PyObject *_wrap_player_class_c_exp_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_c_exp_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_c_exp_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_class_pet_upkeep_div_set(_swigobj,_swigval) (_swigobj->pet_upkeep_div = _swigval,_swigval)
static PyObject *_wrap_player_class_pet_upkeep_div_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    byte  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_class_pet_upkeep_div_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (byte )player_class_pet_upkeep_div_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_class_pet_upkeep_div_get(_swigobj) ((byte ) _swigobj->pet_upkeep_div)
static PyObject *_wrap_player_class_pet_upkeep_div_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    byte  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_pet_upkeep_div_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (byte )player_class_pet_upkeep_div_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

static s16b  player_class_str_mod_set(struct player_class *obj, s16b val) {
{
	obj->c_adj[A_STR] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_class_str_mod_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_str_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_str_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_str_mod_get(struct player_class *obj) {
    s16b  result;
{
	result = obj->c_adj[A_STR];
}
    return result;
}
static PyObject *_wrap_player_class_str_mod_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_str_mod_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_str_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_int_mod_set(struct player_class *obj, s16b val) {
{
	obj->c_adj[A_INT] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_class_int_mod_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_int_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_int_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_int_mod_get(struct player_class *obj) {
    s16b  result;
{
	result = obj->c_adj[A_INT];
}
    return result;
}
static PyObject *_wrap_player_class_int_mod_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_int_mod_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_int_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_wis_mod_set(struct player_class *obj, s16b val) {
{
	obj->c_adj[A_WIS] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_class_wis_mod_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_wis_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_wis_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_wis_mod_get(struct player_class *obj) {
    s16b  result;
{
	result = obj->c_adj[A_WIS];
}
    return result;
}
static PyObject *_wrap_player_class_wis_mod_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_wis_mod_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_wis_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_dex_mod_set(struct player_class *obj, s16b val) {
{
	obj->c_adj[A_DEX] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_class_dex_mod_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_dex_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_dex_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_dex_mod_get(struct player_class *obj) {
    s16b  result;
{
	result = obj->c_adj[A_DEX];
}
    return result;
}
static PyObject *_wrap_player_class_dex_mod_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_dex_mod_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_dex_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_con_mod_set(struct player_class *obj, s16b val) {
{
	obj->c_adj[A_CON] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_class_con_mod_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_con_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_con_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_con_mod_get(struct player_class *obj) {
    s16b  result;
{
	result = obj->c_adj[A_CON];
}
    return result;
}
static PyObject *_wrap_player_class_con_mod_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_con_mod_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_con_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_chr_mod_set(struct player_class *obj, s16b val) {
{
	obj->c_adj[A_CHR] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_class_chr_mod_set(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result,_arg1;
    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_class_chr_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_chr_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_class_chr_mod_get(struct player_class *obj) {
    s16b  result;
{
	result = obj->c_adj[A_CHR];
}
    return result;
}
static PyObject *_wrap_player_class_chr_mod_get(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    s16b  _result;
    self = self;
    if(!PyArg_ParseTuple(args,"O:player_class_chr_mod_get",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    _result = (s16b )player_class_chr_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static struct player_class *new_player_class() {
			cp_ptr = (player_class*) malloc(sizeof(player_class));
			return cp_ptr;
		}

static PyObject *_wrap_new_player_class(PyObject *self, PyObject *args) {
    struct player_class  *_result;
    PyObject  *_resultobj;
    self = self;
    if(!PyArg_ParseTuple(args,":new_player_class")) 
        return NULL;
    _result = (struct player_class *)new_player_class();
    _resultobj = SWIG_NewPointerObj((void *) _result, SWIGTYPE_player_class_p);
    return _resultobj;
}

static void delete_player_class(struct player_class *self) {
			free(self);
		}
static PyObject *_wrap_delete_player_class(PyObject *self, PyObject *args) {
    struct player_class  *_arg0;
    PyObject  *_resultobj,*_argo0=0;
    self = self;
    if(!PyArg_ParseTuple(args,"O:delete_player_class",&_argo0)) 
        return NULL;
    if ((SWIG_ConvertPtr(_argo0,(void **) &_arg0,SWIGTYPE_player_class_p,1)) == -1) return NULL;
    delete_player_class(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef pclasscMethods[] = {
	 { "delete_player_class", _wrap_delete_player_class, METH_VARARGS },
	 { "new_player_class", _wrap_new_player_class, METH_VARARGS },
	 { "player_class_chr_mod_get", _wrap_player_class_chr_mod_get, METH_VARARGS },
	 { "player_class_chr_mod_set", _wrap_player_class_chr_mod_set, METH_VARARGS },
	 { "player_class_con_mod_get", _wrap_player_class_con_mod_get, METH_VARARGS },
	 { "player_class_con_mod_set", _wrap_player_class_con_mod_set, METH_VARARGS },
	 { "player_class_dex_mod_get", _wrap_player_class_dex_mod_get, METH_VARARGS },
	 { "player_class_dex_mod_set", _wrap_player_class_dex_mod_set, METH_VARARGS },
	 { "player_class_wis_mod_get", _wrap_player_class_wis_mod_get, METH_VARARGS },
	 { "player_class_wis_mod_set", _wrap_player_class_wis_mod_set, METH_VARARGS },
	 { "player_class_int_mod_get", _wrap_player_class_int_mod_get, METH_VARARGS },
	 { "player_class_int_mod_set", _wrap_player_class_int_mod_set, METH_VARARGS },
	 { "player_class_str_mod_get", _wrap_player_class_str_mod_get, METH_VARARGS },
	 { "player_class_str_mod_set", _wrap_player_class_str_mod_set, METH_VARARGS },
	 { "player_class_pet_upkeep_div_get", _wrap_player_class_pet_upkeep_div_get, METH_VARARGS },
	 { "player_class_pet_upkeep_div_set", _wrap_player_class_pet_upkeep_div_set, METH_VARARGS },
	 { "player_class_c_exp_get", _wrap_player_class_c_exp_get, METH_VARARGS },
	 { "player_class_c_exp_set", _wrap_player_class_c_exp_set, METH_VARARGS },
	 { "player_class_c_mhp_get", _wrap_player_class_c_mhp_get, METH_VARARGS },
	 { "player_class_c_mhp_set", _wrap_player_class_c_mhp_set, METH_VARARGS },
	 { "player_class_x_thb_get", _wrap_player_class_x_thb_get, METH_VARARGS },
	 { "player_class_x_thb_set", _wrap_player_class_x_thb_set, METH_VARARGS },
	 { "player_class_x_thn_get", _wrap_player_class_x_thn_get, METH_VARARGS },
	 { "player_class_x_thn_set", _wrap_player_class_x_thn_set, METH_VARARGS },
	 { "player_class_x_fos_get", _wrap_player_class_x_fos_get, METH_VARARGS },
	 { "player_class_x_fos_set", _wrap_player_class_x_fos_set, METH_VARARGS },
	 { "player_class_x_srh_get", _wrap_player_class_x_srh_get, METH_VARARGS },
	 { "player_class_x_srh_set", _wrap_player_class_x_srh_set, METH_VARARGS },
	 { "player_class_x_stl_get", _wrap_player_class_x_stl_get, METH_VARARGS },
	 { "player_class_x_stl_set", _wrap_player_class_x_stl_set, METH_VARARGS },
	 { "player_class_x_sav_get", _wrap_player_class_x_sav_get, METH_VARARGS },
	 { "player_class_x_sav_set", _wrap_player_class_x_sav_set, METH_VARARGS },
	 { "player_class_x_dev_get", _wrap_player_class_x_dev_get, METH_VARARGS },
	 { "player_class_x_dev_set", _wrap_player_class_x_dev_set, METH_VARARGS },
	 { "player_class_x_dis_get", _wrap_player_class_x_dis_get, METH_VARARGS },
	 { "player_class_x_dis_set", _wrap_player_class_x_dis_set, METH_VARARGS },
	 { "player_class_c_thb_get", _wrap_player_class_c_thb_get, METH_VARARGS },
	 { "player_class_c_thb_set", _wrap_player_class_c_thb_set, METH_VARARGS },
	 { "player_class_c_thn_get", _wrap_player_class_c_thn_get, METH_VARARGS },
	 { "player_class_c_thn_set", _wrap_player_class_c_thn_set, METH_VARARGS },
	 { "player_class_c_fos_get", _wrap_player_class_c_fos_get, METH_VARARGS },
	 { "player_class_c_fos_set", _wrap_player_class_c_fos_set, METH_VARARGS },
	 { "player_class_c_srh_get", _wrap_player_class_c_srh_get, METH_VARARGS },
	 { "player_class_c_srh_set", _wrap_player_class_c_srh_set, METH_VARARGS },
	 { "player_class_c_stl_get", _wrap_player_class_c_stl_get, METH_VARARGS },
	 { "player_class_c_stl_set", _wrap_player_class_c_stl_set, METH_VARARGS },
	 { "player_class_c_sav_get", _wrap_player_class_c_sav_get, METH_VARARGS },
	 { "player_class_c_sav_set", _wrap_player_class_c_sav_set, METH_VARARGS },
	 { "player_class_c_dev_get", _wrap_player_class_c_dev_get, METH_VARARGS },
	 { "player_class_c_dev_set", _wrap_player_class_c_dev_set, METH_VARARGS },
	 { "player_class_c_dis_get", _wrap_player_class_c_dis_get, METH_VARARGS },
	 { "player_class_c_dis_set", _wrap_player_class_c_dis_set, METH_VARARGS },
	 { "player_class_c_adj_get", _wrap_player_class_c_adj_get, METH_VARARGS },
	 { "player_class_title_get", _wrap_player_class_title_get, METH_VARARGS },
	 { "player_class_title_set", _wrap_player_class_title_set, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
static _swig_type_info _swigt__player_class_p[] = {{"_player_class_p",0},{"_player_class_p",0},{0}};
static _swig_type_info _swigt__s16b_p[] = {{"_s16b_p",0},{"_s16b_p",0},{ "_signed_short_p",0}, {0}};

static _swig_type_info *_swig_types_initial[] = {
_swigt__player_class_p, 
_swigt__s16b_p, 
0
};

static _swig_const_info _swig_const_table[] = {
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initpclassc(void) {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("pclassc", pclasscMethods);
	 d = PyModule_GetDict(m);
    {
        int i;
        for (i = 0; _swig_types_initial[i]; i++) {
            _swig_types[i] = SWIG_TypeRegister(_swig_types_initial[i]);
        }
    }
    SWIG_InstallConstants(d,_swig_const_table);

}
