/*
 * FILE : .\src\prace_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Build 789)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 * Revision 1.2  1999/08/13 22:27:51  beazley
 * Misc
 *
 * Revision 1.1.1.1  1999/02/28 02:00:55  beazley
 * Swig1.1
 *
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a) __declspec(dllexport) a
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a) a _export
#	else
#	    define SWIGEXPORT(a) a
#	endif
#   endif
#else
#   define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#endif

#ifndef SWIGSTATICRUNTIME
#define SWIGSTATICRUNTIME(a) static a
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATICRUNTIME(void) 
SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATICRUNTIME(char *) 
SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start > end) sp = 0;
	  /* Try to find a match for this */
	  while (start <= end) {
	    if (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	    }
	    sp++;
	    start++;
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

/* New object-based GetPointer function. This uses the Python abstract
 * object interface to automatically dereference the 'this' attribute
 * of shadow objects. */

SWIGSTATICRUNTIME(char *)
SWIG_GetPtrObj(PyObject *obj, void **ptr, char *type) {
  PyObject *sobj = obj;
  char     *str;
  if (!PyString_Check(obj)) {
    sobj = PyObject_GetAttrString(obj,"this");
    if (!sobj) return "";
  }
  str = PyString_AsString(sobj);
  return SWIG_GetPtr(str,ptr,type);
}

#ifdef __cplusplus
}
#endif


#define SWIG_init    initpracec

#define SWIG_name    "pracec"


#include "angband.h"

#ifdef __cplusplus
extern "C" {
#endif
static cptr  player_race_title_set(struct player_race *obj, cptr val) {
{
	obj->title = string_make(val);
}
    return (cptr ) val;
}
static PyObject *_wrap_player_race_title_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    cptr  _result;
    struct player_race * _arg0;
    cptr  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Os:player_race_title_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_title_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (cptr )player_race_title_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

static cptr  player_race_title_get(struct player_race *obj) {
    cptr  result;
{
	result = obj->title;
}
    return result;
}
static PyObject *_wrap_player_race_title_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    cptr  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_title_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_title_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (cptr )player_race_title_get(_arg0);
    _resultobj = Py_BuildValue("s", _result);
    return _resultobj;
}

#define player_race_r_adj_get(_swigobj) ((s16b *) _swigobj->r_adj)
static PyObject *_wrap_player_race_r_adj_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b * _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_adj_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_adj_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b *)player_race_r_adj_get(_arg0);
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_s16b_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

#define player_race_r_dis_set(_swigobj,_swigval) (_swigobj->r_dis = _swigval,_swigval)
static PyObject *_wrap_player_race_r_dis_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_dis_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_dis_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_dis_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_dis_get(_swigobj) ((s16b ) _swigobj->r_dis)
static PyObject *_wrap_player_race_r_dis_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_dis_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_dis_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_dis_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_dev_set(_swigobj,_swigval) (_swigobj->r_dev = _swigval,_swigval)
static PyObject *_wrap_player_race_r_dev_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_dev_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_dev_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_dev_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_dev_get(_swigobj) ((s16b ) _swigobj->r_dev)
static PyObject *_wrap_player_race_r_dev_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_dev_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_dev_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_dev_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_sav_set(_swigobj,_swigval) (_swigobj->r_sav = _swigval,_swigval)
static PyObject *_wrap_player_race_r_sav_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_sav_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_sav_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_sav_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_sav_get(_swigobj) ((s16b ) _swigobj->r_sav)
static PyObject *_wrap_player_race_r_sav_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_sav_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_sav_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_sav_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_stl_set(_swigobj,_swigval) (_swigobj->r_stl = _swigval,_swigval)
static PyObject *_wrap_player_race_r_stl_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_stl_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_stl_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_stl_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_stl_get(_swigobj) ((s16b ) _swigobj->r_stl)
static PyObject *_wrap_player_race_r_stl_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_stl_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_stl_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_stl_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_srh_set(_swigobj,_swigval) (_swigobj->r_srh = _swigval,_swigval)
static PyObject *_wrap_player_race_r_srh_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_srh_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_srh_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_srh_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_srh_get(_swigobj) ((s16b ) _swigobj->r_srh)
static PyObject *_wrap_player_race_r_srh_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_srh_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_srh_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_srh_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_fos_set(_swigobj,_swigval) (_swigobj->r_fos = _swigval,_swigval)
static PyObject *_wrap_player_race_r_fos_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_fos_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_fos_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_fos_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_fos_get(_swigobj) ((s16b ) _swigobj->r_fos)
static PyObject *_wrap_player_race_r_fos_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_fos_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_fos_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_fos_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_thn_set(_swigobj,_swigval) (_swigobj->r_thn = _swigval,_swigval)
static PyObject *_wrap_player_race_r_thn_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_thn_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_thn_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_thn_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_thn_get(_swigobj) ((s16b ) _swigobj->r_thn)
static PyObject *_wrap_player_race_r_thn_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_thn_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_thn_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_thn_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_thb_set(_swigobj,_swigval) (_swigobj->r_thb = _swigval,_swigval)
static PyObject *_wrap_player_race_r_thb_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_r_thb_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_thb_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_thb_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_thb_get(_swigobj) ((s16b ) _swigobj->r_thb)
static PyObject *_wrap_player_race_r_thb_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_thb_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_thb_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_r_thb_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_r_mhp_set(_swigobj,_swigval) (_swigobj->r_mhp = _swigval,_swigval)
static PyObject *_wrap_player_race_r_mhp_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_r_mhp_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_mhp_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_r_mhp_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_r_mhp_get(_swigobj) ((byte ) _swigobj->r_mhp)
static PyObject *_wrap_player_race_r_mhp_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_mhp_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_mhp_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_r_mhp_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_r_exp_set(_swigobj,_swigval) (_swigobj->r_exp = _swigval,_swigval)
static PyObject *_wrap_player_race_r_exp_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_r_exp_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_exp_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_r_exp_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_r_exp_get(_swigobj) ((byte ) _swigobj->r_exp)
static PyObject *_wrap_player_race_r_exp_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_r_exp_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_r_exp_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_r_exp_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_b_age_set(_swigobj,_swigval) (_swigobj->b_age = _swigval,_swigval)
static PyObject *_wrap_player_race_b_age_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_b_age_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_b_age_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_b_age_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_b_age_get(_swigobj) ((byte ) _swigobj->b_age)
static PyObject *_wrap_player_race_b_age_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_b_age_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_b_age_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_b_age_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_age_set(_swigobj,_swigval) (_swigobj->m_age = _swigval,_swigval)
static PyObject *_wrap_player_race_m_age_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_m_age_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_age_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_age_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_age_get(_swigobj) ((byte ) _swigobj->m_age)
static PyObject *_wrap_player_race_m_age_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_m_age_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_age_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_age_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_b_ht_set(_swigobj,_swigval) (_swigobj->m_b_ht = _swigval,_swigval)
static PyObject *_wrap_player_race_m_b_ht_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_m_b_ht_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_b_ht_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_b_ht_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_b_ht_get(_swigobj) ((byte ) _swigobj->m_b_ht)
static PyObject *_wrap_player_race_m_b_ht_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_m_b_ht_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_b_ht_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_b_ht_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_m_ht_set(_swigobj,_swigval) (_swigobj->m_m_ht = _swigval,_swigval)
static PyObject *_wrap_player_race_m_m_ht_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_m_m_ht_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_m_ht_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_m_ht_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_m_ht_get(_swigobj) ((byte ) _swigobj->m_m_ht)
static PyObject *_wrap_player_race_m_m_ht_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_m_m_ht_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_m_ht_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_m_ht_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_b_wt_set(_swigobj,_swigval) (_swigobj->m_b_wt = _swigval,_swigval)
static PyObject *_wrap_player_race_m_b_wt_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_m_b_wt_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_b_wt_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_b_wt_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_b_wt_get(_swigobj) ((byte ) _swigobj->m_b_wt)
static PyObject *_wrap_player_race_m_b_wt_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_m_b_wt_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_b_wt_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_b_wt_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_m_wt_set(_swigobj,_swigval) (_swigobj->m_m_wt = _swigval,_swigval)
static PyObject *_wrap_player_race_m_m_wt_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_m_m_wt_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_m_wt_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_m_wt_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_m_m_wt_get(_swigobj) ((byte ) _swigobj->m_m_wt)
static PyObject *_wrap_player_race_m_m_wt_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_m_m_wt_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_m_m_wt_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_m_m_wt_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_b_ht_set(_swigobj,_swigval) (_swigobj->f_b_ht = _swigval,_swigval)
static PyObject *_wrap_player_race_f_b_ht_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_f_b_ht_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_b_ht_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_b_ht_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_b_ht_get(_swigobj) ((byte ) _swigobj->f_b_ht)
static PyObject *_wrap_player_race_f_b_ht_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_f_b_ht_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_b_ht_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_b_ht_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_m_ht_set(_swigobj,_swigval) (_swigobj->f_m_ht = _swigval,_swigval)
static PyObject *_wrap_player_race_f_m_ht_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_f_m_ht_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_m_ht_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_m_ht_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_m_ht_get(_swigobj) ((byte ) _swigobj->f_m_ht)
static PyObject *_wrap_player_race_f_m_ht_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_f_m_ht_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_m_ht_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_m_ht_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_b_wt_set(_swigobj,_swigval) (_swigobj->f_b_wt = _swigval,_swigval)
static PyObject *_wrap_player_race_f_b_wt_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_f_b_wt_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_b_wt_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_b_wt_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_b_wt_get(_swigobj) ((byte ) _swigobj->f_b_wt)
static PyObject *_wrap_player_race_f_b_wt_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_f_b_wt_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_b_wt_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_b_wt_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_m_wt_set(_swigobj,_swigval) (_swigobj->f_m_wt = _swigval,_swigval)
static PyObject *_wrap_player_race_f_m_wt_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_f_m_wt_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_m_wt_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_m_wt_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_f_m_wt_get(_swigobj) ((byte ) _swigobj->f_m_wt)
static PyObject *_wrap_player_race_f_m_wt_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_f_m_wt_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_f_m_wt_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_f_m_wt_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_infra_set(_swigobj,_swigval) (_swigobj->infra = _swigval,_swigval)
static PyObject *_wrap_player_race_infra_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    byte  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Ob:player_race_infra_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_infra_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_infra_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_infra_get(_swigobj) ((byte ) _swigobj->infra)
static PyObject *_wrap_player_race_infra_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    byte  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_infra_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_infra_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (byte )player_race_infra_get(_arg0);
    _resultobj = Py_BuildValue("b",_result);
    return _resultobj;
}

#define player_race_choice_set(_swigobj,_swigval) (_swigobj->choice = _swigval,_swigval)
static PyObject *_wrap_player_race_choice_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    u16b  _result;
    struct player_race * _arg0;
    u16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_choice_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_choice_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (u16b )player_race_choice_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

#define player_race_choice_get(_swigobj) ((u16b ) _swigobj->choice)
static PyObject *_wrap_player_race_choice_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    u16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_choice_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_choice_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (u16b )player_race_choice_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_str_mod_set(struct player_race *obj, s16b val) {
{
	obj->r_adj[A_STR] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_race_str_mod_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_str_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_str_mod_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_str_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_str_mod_get(struct player_race *obj) {
    s16b  result;
{
	result = obj->r_adj[A_STR];
}
    return result;
}
static PyObject *_wrap_player_race_str_mod_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_str_mod_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_str_mod_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_str_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_int_mod_set(struct player_race *obj, s16b val) {
{
	obj->r_adj[A_INT] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_race_int_mod_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_int_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_int_mod_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_int_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_int_mod_get(struct player_race *obj) {
    s16b  result;
{
	result = obj->r_adj[A_INT];
}
    return result;
}
static PyObject *_wrap_player_race_int_mod_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_int_mod_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_int_mod_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_int_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_wis_mod_set(struct player_race *obj, s16b val) {
{
	obj->r_adj[A_WIS] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_race_wis_mod_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_wis_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_wis_mod_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_wis_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_wis_mod_get(struct player_race *obj) {
    s16b  result;
{
	result = obj->r_adj[A_WIS];
}
    return result;
}
static PyObject *_wrap_player_race_wis_mod_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_wis_mod_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_wis_mod_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_wis_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_dex_mod_set(struct player_race *obj, s16b val) {
{
	obj->r_adj[A_DEX] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_race_dex_mod_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_dex_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_dex_mod_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_dex_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_dex_mod_get(struct player_race *obj) {
    s16b  result;
{
	result = obj->r_adj[A_DEX];
}
    return result;
}
static PyObject *_wrap_player_race_dex_mod_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_dex_mod_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_dex_mod_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_dex_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_con_mod_set(struct player_race *obj, s16b val) {
{
	obj->r_adj[A_CON] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_race_con_mod_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_con_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_con_mod_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_con_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_con_mod_get(struct player_race *obj) {
    s16b  result;
{
	result = obj->r_adj[A_CON];
}
    return result;
}
static PyObject *_wrap_player_race_con_mod_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_con_mod_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_con_mod_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_con_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_chr_mod_set(struct player_race *obj, s16b val) {
{
	obj->r_adj[A_CHR] = val;
}
    return (s16b ) val;
}
static PyObject *_wrap_player_race_chr_mod_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    s16b  _arg1;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oh:player_race_chr_mod_set",&_argo0,&_arg1)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_chr_mod_set. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_chr_mod_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static s16b  player_race_chr_mod_get(struct player_race *obj) {
    s16b  result;
{
	result = obj->r_adj[A_CHR];
}
    return result;
}
static PyObject *_wrap_player_race_chr_mod_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:player_race_chr_mod_get",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of player_race_chr_mod_get. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    _result = (s16b )player_race_chr_mod_get(_arg0);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static struct player_race *new_player_race() {
			rp_ptr = (player_race*) malloc(sizeof(player_race));
			return rp_ptr;
		}

static PyObject *_wrap_new_player_race(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct player_race * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_player_race")) 
        return NULL;
    _result = (struct player_race *)new_player_race();
    if (_result) {
        SWIG_MakePtr(_ptemp, (char *) _result,"_struct_player_race_p");
        _resultobj = Py_BuildValue("s",_ptemp);
    } else {
        Py_INCREF(Py_None);
        _resultobj = Py_None;
    }
    return _resultobj;
}

static void delete_player_race(struct player_race *self) {
			free(self);
		}
static PyObject *_wrap_delete_player_race(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    struct player_race * _arg0;
    PyObject * _argo0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:delete_player_race",&_argo0)) 
        return NULL;
    if (_argo0) {
        if (_argo0 == Py_None) { _arg0 = NULL; }
        else if (SWIG_GetPtrObj(_argo0,(void **) &_arg0,"_struct_player_race_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_player_race. Expected _struct_player_race_p.");
        return NULL;
        }
    }
    delete_player_race(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef pracecMethods[] = {
	 { "delete_player_race", _wrap_delete_player_race, METH_VARARGS },
	 { "new_player_race", _wrap_new_player_race, METH_VARARGS },
	 { "player_race_chr_mod_get", _wrap_player_race_chr_mod_get, METH_VARARGS },
	 { "player_race_chr_mod_set", _wrap_player_race_chr_mod_set, METH_VARARGS },
	 { "player_race_con_mod_get", _wrap_player_race_con_mod_get, METH_VARARGS },
	 { "player_race_con_mod_set", _wrap_player_race_con_mod_set, METH_VARARGS },
	 { "player_race_dex_mod_get", _wrap_player_race_dex_mod_get, METH_VARARGS },
	 { "player_race_dex_mod_set", _wrap_player_race_dex_mod_set, METH_VARARGS },
	 { "player_race_wis_mod_get", _wrap_player_race_wis_mod_get, METH_VARARGS },
	 { "player_race_wis_mod_set", _wrap_player_race_wis_mod_set, METH_VARARGS },
	 { "player_race_int_mod_get", _wrap_player_race_int_mod_get, METH_VARARGS },
	 { "player_race_int_mod_set", _wrap_player_race_int_mod_set, METH_VARARGS },
	 { "player_race_str_mod_get", _wrap_player_race_str_mod_get, METH_VARARGS },
	 { "player_race_str_mod_set", _wrap_player_race_str_mod_set, METH_VARARGS },
	 { "player_race_choice_get", _wrap_player_race_choice_get, METH_VARARGS },
	 { "player_race_choice_set", _wrap_player_race_choice_set, METH_VARARGS },
	 { "player_race_infra_get", _wrap_player_race_infra_get, METH_VARARGS },
	 { "player_race_infra_set", _wrap_player_race_infra_set, METH_VARARGS },
	 { "player_race_f_m_wt_get", _wrap_player_race_f_m_wt_get, METH_VARARGS },
	 { "player_race_f_m_wt_set", _wrap_player_race_f_m_wt_set, METH_VARARGS },
	 { "player_race_f_b_wt_get", _wrap_player_race_f_b_wt_get, METH_VARARGS },
	 { "player_race_f_b_wt_set", _wrap_player_race_f_b_wt_set, METH_VARARGS },
	 { "player_race_f_m_ht_get", _wrap_player_race_f_m_ht_get, METH_VARARGS },
	 { "player_race_f_m_ht_set", _wrap_player_race_f_m_ht_set, METH_VARARGS },
	 { "player_race_f_b_ht_get", _wrap_player_race_f_b_ht_get, METH_VARARGS },
	 { "player_race_f_b_ht_set", _wrap_player_race_f_b_ht_set, METH_VARARGS },
	 { "player_race_m_m_wt_get", _wrap_player_race_m_m_wt_get, METH_VARARGS },
	 { "player_race_m_m_wt_set", _wrap_player_race_m_m_wt_set, METH_VARARGS },
	 { "player_race_m_b_wt_get", _wrap_player_race_m_b_wt_get, METH_VARARGS },
	 { "player_race_m_b_wt_set", _wrap_player_race_m_b_wt_set, METH_VARARGS },
	 { "player_race_m_m_ht_get", _wrap_player_race_m_m_ht_get, METH_VARARGS },
	 { "player_race_m_m_ht_set", _wrap_player_race_m_m_ht_set, METH_VARARGS },
	 { "player_race_m_b_ht_get", _wrap_player_race_m_b_ht_get, METH_VARARGS },
	 { "player_race_m_b_ht_set", _wrap_player_race_m_b_ht_set, METH_VARARGS },
	 { "player_race_m_age_get", _wrap_player_race_m_age_get, METH_VARARGS },
	 { "player_race_m_age_set", _wrap_player_race_m_age_set, METH_VARARGS },
	 { "player_race_b_age_get", _wrap_player_race_b_age_get, METH_VARARGS },
	 { "player_race_b_age_set", _wrap_player_race_b_age_set, METH_VARARGS },
	 { "player_race_r_exp_get", _wrap_player_race_r_exp_get, METH_VARARGS },
	 { "player_race_r_exp_set", _wrap_player_race_r_exp_set, METH_VARARGS },
	 { "player_race_r_mhp_get", _wrap_player_race_r_mhp_get, METH_VARARGS },
	 { "player_race_r_mhp_set", _wrap_player_race_r_mhp_set, METH_VARARGS },
	 { "player_race_r_thb_get", _wrap_player_race_r_thb_get, METH_VARARGS },
	 { "player_race_r_thb_set", _wrap_player_race_r_thb_set, METH_VARARGS },
	 { "player_race_r_thn_get", _wrap_player_race_r_thn_get, METH_VARARGS },
	 { "player_race_r_thn_set", _wrap_player_race_r_thn_set, METH_VARARGS },
	 { "player_race_r_fos_get", _wrap_player_race_r_fos_get, METH_VARARGS },
	 { "player_race_r_fos_set", _wrap_player_race_r_fos_set, METH_VARARGS },
	 { "player_race_r_srh_get", _wrap_player_race_r_srh_get, METH_VARARGS },
	 { "player_race_r_srh_set", _wrap_player_race_r_srh_set, METH_VARARGS },
	 { "player_race_r_stl_get", _wrap_player_race_r_stl_get, METH_VARARGS },
	 { "player_race_r_stl_set", _wrap_player_race_r_stl_set, METH_VARARGS },
	 { "player_race_r_sav_get", _wrap_player_race_r_sav_get, METH_VARARGS },
	 { "player_race_r_sav_set", _wrap_player_race_r_sav_set, METH_VARARGS },
	 { "player_race_r_dev_get", _wrap_player_race_r_dev_get, METH_VARARGS },
	 { "player_race_r_dev_set", _wrap_player_race_r_dev_set, METH_VARARGS },
	 { "player_race_r_dis_get", _wrap_player_race_r_dis_get, METH_VARARGS },
	 { "player_race_r_dis_set", _wrap_player_race_r_dis_set, METH_VARARGS },
	 { "player_race_r_adj_get", _wrap_player_race_r_adj_get, METH_VARARGS },
	 { "player_race_title_get", _wrap_player_race_title_get, METH_VARARGS },
	 { "player_race_title_set", _wrap_player_race_title_set, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initpracec() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("pracec", pracecMethods);
	 d = PyModule_GetDict(m);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_byte","_unsigned_char",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_cptr","_char_p",0);
	 SWIG_RegisterMapping("_char_p","_cptr",0);
	 SWIG_RegisterMapping("_struct_player_race","_player_race",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_s32b",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_s16b","_signed_short",0);
	 SWIG_RegisterMapping("_s16b","_short",0);
	 SWIG_RegisterMapping("_unsigned_short","_u16b",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_s32b","_signed_int",0);
	 SWIG_RegisterMapping("_s32b","_int",0);
	 SWIG_RegisterMapping("_signed_short","_s16b",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_char","_byte",0);
	 SWIG_RegisterMapping("_unsigned_int","_u32b",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_u16b",0);
	 SWIG_RegisterMapping("_short","_s16b",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_u32b",0);
	 SWIG_RegisterMapping("_int","_s32b",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 SWIG_RegisterMapping("_u16b","_unsigned_short",0);
	 SWIG_RegisterMapping("_u16b","_short",0);
	 SWIG_RegisterMapping("_u32b","_unsigned_int",0);
	 SWIG_RegisterMapping("_u32b","_int",0);
	 SWIG_RegisterMapping("_player_race","_struct_player_race",0);
}
