/*
 * FILE : random_wrap.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Build 883)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * Contains variable linking and pointer type-checking code.
 ************************************************************************/

#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"

/* Definitions for Windows/Unix exporting */
#if defined(_WIN32) || defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a) __declspec(dllexport) a
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a) a _export
#	else
#	    define SWIGEXPORT(a) a
#	endif
#   endif
#else
#   define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGSTATICRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGSTATICRUNTIME(a) static a
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATICRUNTIME(PyObject *)
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATICRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}

/* -----------------------------------------------------------------------------
 * Pointer type-checking
 * ----------------------------------------------------------------------------- */

/* SWIG pointer structure */
typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */
typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */
#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Register a new datatype with the type-checker */
SWIGSTATICRUNTIME(void) 
SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {
  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */
  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
  }

  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++) {
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN++];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
  }

  /* Check for existing entries */
  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */
SWIGSTATICRUNTIME(void) 
SWIG_MakePtr(char *c, const void *ptr, char *type) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[24], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, type);
  } else {
    strcpy (c, "NULL");
  }
}

/* Function for getting a pointer value */
SWIGSTATICRUNTIME(char *) 
SWIG_GetPtr(char *c, void **ptr, char *t)
{
  unsigned long p;
  char temp_type[256], *name;
  int  i, len, start, end;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  register int d;

  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) return (char *) 0;
    else c;
  }
  c++;
  /* Extract hex value from pointer */
  while (d = *c) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if ((!t) || (strcmp(t,c)==0)) return (char *) 0;

  if (!SwigPtrSort) {
    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
    for (i = 0; i < 256; i++) SwigStart[i] = SwigPtrN;
    for (i = SwigPtrN-1; i >= 0; i--) SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
    for (i = 255; i >= 1; i--) {
      if (SwigStart[i-1] > SwigStart[i])
	SwigStart[i-1] = SwigStart[i];
    }
    SwigPtrSort = 1;
    for (i = 0; i < SWIG_CACHESIZE; i++) SwigCache[i].stat = 0;
  }
  /* First check cache for matches.  Uses last cache value as starting point */
  cache = &SwigCache[SwigLastCache];
  for (i = 0; i < SWIG_CACHESIZE; i++) {
    if (cache->stat && (strcmp(t,cache->name) == 0) && (strcmp(c,cache->mapped) == 0)) {
      cache->stat++;
      if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
      return (char *) 0;
    }
    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
    if (!SwigLastCache) cache = SwigCache;
    else cache++;
  }
  /* Type mismatch.  Look through type-mapping table */
  start = SwigStart[(int) t[1]];
  end = SwigStart[(int) t[1]+1];
  sp = &SwigPtrTable[start];

  /* Try to find a match */
  while (start <= end) {
    if (strncmp(t,sp->name,sp->len) == 0) {
      name = sp->name;
      len = sp->len;
      tp = sp->next;
      /* Try to find entry for our given datatype */
      while(tp) {
	if (tp->len >= 255) {
	  return c;
	}
	strcpy(temp_type,tp->name);
	strncat(temp_type,t+len,255-tp->len);
	if (strcmp(c,temp_type) == 0) {
	  strcpy(SwigCache[SwigCacheIndex].mapped,c);
	  strcpy(SwigCache[SwigCacheIndex].name,t);
	  SwigCache[SwigCacheIndex].stat = 1;
	  SwigCache[SwigCacheIndex].tp = tp;
	  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
	  /* Get pointer value */
	  *ptr = (void *) p;
	  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
	  return (char *) 0;
	}
	tp = tp->next;
      }
    }
    sp++;
    start++;
  }
  return c;
} 

/* New object-based GetPointer function. This uses the Python abstract
 * object interface to automatically dereference the 'this' attribute
 * of shadow objects. */

SWIGSTATICRUNTIME(char *)
SWIG_GetPtrObj(PyObject *obj, void **ptr, char *type) {
  PyObject *sobj = obj;
  char     *str;
  if (!PyString_Check(obj)) {
    sobj = PyObject_GetAttrString(obj,"this");
    if (!sobj) return "";
  }
  str = PyString_AsString(sobj);
  return SWIG_GetPtr(str,ptr,type);
}

#ifdef __cplusplus
}
#endif


#define SWIG_init    initrandom

#define SWIG_name    "random"


#include "angband.h"


	s32b rand_int_temp(u32b m)
	{
		return randint0(m);
	}
extern s32b rand_int_temp(u32b );

	s32b randint_temp(u32b m)
	{
		return randint1(m);
	}
extern s32b randint_temp(u32b );

	/*
	 * Generates a random long integer X where A<=X<=B
	 * The integer X falls along a uniform distribution.
	 * Note: rand_range(0,N-1) == rand_int(N)
	 */
	s32b rand_range_temp(u32b min, u32b max)
	{
		return rand_range(min, max);
	}
extern s32b rand_range_temp(u32b ,u32b );
extern bool  Rand_quick; 
extern u32b  Rand_value; 
extern u16b  Rand_place; 
extern u32b  Rand_state[(63)]; 
extern byte  quick_rand_place; 
extern void Rand_state_init(u32b );
extern s32b Rand_mod(s32b );
extern s32b Rand_div(u32b );
extern s16b randnor(int ,int );
extern s16b damroll(int ,int );
extern s16b maxroll(int ,int );
extern bool quick_rand();
extern void quick_rand_add();
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_rand_int(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s32b  _result;
    u32b  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:rand_int",&_arg0)) 
        return NULL;
    _result = (s32b )rand_int_temp(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_randint(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s32b  _result;
    u32b  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:randint",&_arg0)) 
        return NULL;
    _result = (s32b )randint_temp(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_rand_range(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s32b  _result;
    u32b  _arg0;
    u32b  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ii:rand_range",&_arg0,&_arg1)) 
        return NULL;
    _result = (s32b )rand_range_temp(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static int _wrap_Rand_quick_set(PyObject *val) {
    bool  tval;

    tval = (bool )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'Rand_quick'(bool )");
        return 1; 
    }
    Rand_quick = tval;
    return 0;
}

static PyObject *_wrap_Rand_quick_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) Rand_quick);
    return pyobj;
}

static int _wrap_Rand_value_set(PyObject *val) {
    u32b  tval;

    tval = (u32b )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'Rand_value'(u32b )");
        return 1; 
    }
    Rand_value = tval;
    return 0;
}

static PyObject *_wrap_Rand_value_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) Rand_value);
    return pyobj;
}

static int _wrap_Rand_place_set(PyObject *val) {
    u16b  tval;

    tval = (u16b )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'Rand_place'(u16b )");
        return 1; 
    }
    Rand_place = tval;
    return 0;
}

static PyObject *_wrap_Rand_place_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) Rand_place);
    return pyobj;
}

static int _wrap_Rand_state_set(PyObject *val) {

    PyErr_SetString(PyExc_TypeError,"Variable Rand_state is read-only.");
    return 1;
}

static PyObject *_wrap_Rand_state_get() {
    PyObject * pyobj;
    char ptemp[128];

    SWIG_MakePtr(ptemp, (char *) Rand_state,"_u32b_p");
    pyobj = PyString_FromString(ptemp);
    return pyobj;
}

static int _wrap_quick_rand_place_set(PyObject *val) {
    byte  tval;

    tval = (byte )PyInt_AsLong(val);
    if (PyErr_Occurred()) {
        PyErr_SetString(PyExc_TypeError,"C variable 'quick_rand_place'(byte )");
        return 1; 
    }
    quick_rand_place = tval;
    return 0;
}

static PyObject *_wrap_quick_rand_place_get() {
    PyObject * pyobj;

    pyobj = PyInt_FromLong((long) quick_rand_place);
    return pyobj;
}

static PyObject *_wrap_Rand_state_init(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    u32b  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:Rand_state_init",&_arg0)) 
        return NULL;
    Rand_state_init(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Rand_mod(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s32b  _result;
    s32b  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:Rand_mod",&_arg0)) 
        return NULL;
    _result = (s32b )Rand_mod(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_Rand_div(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s32b  _result;
    u32b  _arg0;

    self = self;
    if(!PyArg_ParseTuple(args,"i:Rand_div",&_arg0)) 
        return NULL;
    _result = (s32b )Rand_div(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_randnor(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    int  _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ii:randnor",&_arg0,&_arg1)) 
        return NULL;
    _result = (s16b )randnor(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_damroll(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    int  _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ii:damroll",&_arg0,&_arg1)) 
        return NULL;
    _result = (s16b )damroll(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_maxroll(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    s16b  _result;
    int  _arg0;
    int  _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ii:maxroll",&_arg0,&_arg1)) 
        return NULL;
    _result = (s16b )maxroll(_arg0,_arg1);
    _resultobj = Py_BuildValue("h",_result);
    return _resultobj;
}

static PyObject *_wrap_quick_rand(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    bool  _result;

    self = self;
    if(!PyArg_ParseTuple(args,":quick_rand")) 
        return NULL;
    _result = (bool )quick_rand();
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_quick_rand_add(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":quick_rand_add")) 
        return NULL;
    quick_rand_add();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyMethodDef randomMethods[] = {
	 { "quick_rand_add", _wrap_quick_rand_add, METH_VARARGS },
	 { "quick_rand", _wrap_quick_rand, METH_VARARGS },
	 { "maxroll", _wrap_maxroll, METH_VARARGS },
	 { "damroll", _wrap_damroll, METH_VARARGS },
	 { "randnor", _wrap_randnor, METH_VARARGS },
	 { "Rand_div", _wrap_Rand_div, METH_VARARGS },
	 { "Rand_mod", _wrap_Rand_mod, METH_VARARGS },
	 { "Rand_state_init", _wrap_Rand_state_init, METH_VARARGS },
	 { "rand_range", _wrap_rand_range, METH_VARARGS },
	 { "randint", _wrap_randint, METH_VARARGS },
	 { "rand_int", _wrap_rand_int, METH_VARARGS },
	 { NULL, NULL }
};
#ifdef __cplusplus
}
#endif
/*
 * This table is used by the pointer type-checker
 */
static struct { char *n1; char *n2; void *(*pcnv)(void *); } _swig_mapping[] = {
    { "_signed_long","_long",0},
    { "_byte","_unsigned_char",0},
    { "_long","_unsigned_long",0},
    { "_long","_signed_long",0},
    { "_cptr","_char_p",0},
    { "_char_p","_cptr",0},
    { "_unsigned_long","_long",0},
    { "_signed_int","_s32b",0},
    { "_signed_int","_int",0},
    { "_s16b","_signed_short",0},
    { "_s16b","_short",0},
    { "_unsigned_short","_u16b",0},
    { "_unsigned_short","_short",0},
    { "_s32b","_signed_int",0},
    { "_s32b","_int",0},
    { "_signed_short","_s16b",0},
    { "_signed_short","_short",0},
    { "_unsigned_char","_byte",0},
    { "_unsigned_int","_u32b",0},
    { "_unsigned_int","_int",0},
    { "_short","_u16b",0},
    { "_short","_s16b",0},
    { "_short","_unsigned_short",0},
    { "_short","_signed_short",0},
    { "_int","_u32b",0},
    { "_int","_s32b",0},
    { "_int","_unsigned_int",0},
    { "_int","_signed_int",0},
    { "_u16b","_unsigned_short",0},
    { "_u16b","_short",0},
    { "_u32b","_unsigned_int",0},
    { "_u32b","_int",0},
{0,0,0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initrandom() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("random", randomMethods);
	 d = PyModule_GetDict(m);
	 PyDict_SetItemString(d,"RAND_DEG", PyInt_FromLong((long) 63));
	 PyDict_SetItemString(d,"cvar", SWIG_globals);
	 SWIG_addvarlink(SWIG_globals,"Rand_quick",_wrap_Rand_quick_get, _wrap_Rand_quick_set);
	 SWIG_addvarlink(SWIG_globals,"Rand_value",_wrap_Rand_value_get, _wrap_Rand_value_set);
	 SWIG_addvarlink(SWIG_globals,"Rand_place",_wrap_Rand_place_get, _wrap_Rand_place_set);
	 SWIG_addvarlink(SWIG_globals,"Rand_state",_wrap_Rand_state_get, _wrap_Rand_state_set);
	 SWIG_addvarlink(SWIG_globals,"quick_rand_place",_wrap_quick_rand_place_get, _wrap_quick_rand_place_set);
{
   int i;
   for (i = 0; _swig_mapping[i].n1; i++)
        SWIG_RegisterMapping(_swig_mapping[i].n1,_swig_mapping[i].n2,_swig_mapping[i].pcnv);
}
}
