set loc ja

::msgcat::mcset $loc Weak Šã
::msgcat::mcset $loc Hungry ‹ó• 
::msgcat::mcset $loc Full –• 
::msgcat::mcset $loc Gorged H‰ß‚¬

::msgcat::mcset $loc Blind –Ó–Ú
::msgcat::mcset $loc Confused ¬—
::msgcat::mcset $loc Afraid ‹°•|
::msgcat::mcset $loc Poisoned “Å
::msgcat::mcset $loc Paralyzed! –ƒáƒó‘ÔI

::msgcat::mcset $loc "Rest %d" "‹x‘§ %d"
::msgcat::mcset $loc "Rest *****"  "‹x‘§ *****"
::msgcat::mcset $loc "Rest &&&&&" "‹x‘§ &&&&&"
::msgcat::mcset $loc "Rep. %d" "‰ñ” %d"
::msgcat::mcset $loc "Repeat %d" "‰ñ” %d"
::msgcat::mcset $loc Searching ’Tõ’†

::msgcat::mcset $loc "Fast (%+d)" "‰Á‘¬ (%+d)"
::msgcat::mcset $loc "Slow (%+d)" "Œ¸‘¬ (%+d)"

::msgcat::mcset $loc Study ŠwK

::msgcat::mcset $loc "Mortal Wound" ’v–½
::msgcat::mcset $loc "Deep gash" ‚Ğ‚Ç‚¢[è
::msgcat::mcset $loc "Severe cut" d
::msgcat::mcset $loc "Nasty cut" ‘å•Ï‚È
::msgcat::mcset $loc "Bad cut" ‚Ğ‚Ç‚¢
::msgcat::mcset $loc "Light cut" Œy
::msgcat::mcset $loc Graze ‚©‚·‚è

::msgcat::mcset $loc "Knocked out" ˆÓ¯•s–¾—Ä
::msgcat::mcset $loc "Heavy stun" ‚Ğ‚Ç‚­NO
::msgcat::mcset $loc Stun NO

::msgcat::mcset $loc Wizard ƒEƒBƒU[ƒh
::msgcat::mcset $loc Winner Ÿ—˜Ò

#
# Extra status messages
#
::msgcat::mcset $loc Blessed j•Ÿ
::msgcat::mcset $loc Hero ƒq[ƒ[
::msgcat::mcset $loc Berserk ƒo[ƒTƒN
::msgcat::mcset $loc "Res Acid" ‘Ï_
::msgcat::mcset $loc "Res Cold" ‘Ï—â
::msgcat::mcset $loc "Res Elec" ‘Ï“d
::msgcat::mcset $loc "Res Fire" ‘Ï‰Î
::msgcat::mcset $loc "Res Poison" ‘Ï“Å
::msgcat::mcset $loc "Prot Evil" ‘Şˆ«
::msgcat::mcset $loc Shield ƒV[ƒ‹ƒh
::msgcat::mcset $loc Invulnerable –³“G

::msgcat::mcset $loc Faster ‰Á‘¬
::msgcat::mcset $loc Slower Œ¸‘¬
::msgcat::mcset $loc Infravision ÔŠOü‹—Í
::msgcat::mcset $loc "See Invis" “§–¾‘Ì‹”F
::msgcat::mcset $loc Recall ‹AŠÒ
::msgcat::mcset $loc Hallucinate Œ¶Šo

::msgcat::mcset $loc ESP
::msgcat::mcset $loc Wraith —H‘Ì

