set loc ja

# Window title
::msgcat::mcset $loc Recall 情報

# Monster name
::msgcat::mcset $loc "The " " "

# Pet commands
::msgcat::mcset $loc "Dismiss pets" ペットを放す
::msgcat::mcset $loc "Stay close" 近くにいろ
::msgcat::mcset $loc "Follow me" ついて来い
::msgcat::mcset $loc "Seek and destroy" 敵を探して倒せ
::msgcat::mcset $loc "Give me space" 少し離れろ
::msgcat::mcset $loc "Stay away" 離れろ
::msgcat::mcset $loc "Allow open doors" ドアを開けさせる
::msgcat::mcset $loc "Disallow open doors" ドアを開けさせない
::msgcat::mcset $loc "Allow pickup items" アイテムを拾わせる
::msgcat::mcset $loc "Disallow pickup items" アイテムを拾わせない

