set loc en

# Window title
::msgcat::mcset $loc "%s Hall of Fame"

# Score menu
::msgcat::mcset $loc Score
::msgcat::mcset $loc "Dump Scores"
::msgcat::mcset $loc "Show Record"

# Sort menu
::msgcat::mcset $loc Sort
::msgcat::mcset $loc Class
::msgcat::mcset $loc Name
::msgcat::mcset $loc Race
::msgcat::mcset $loc Score
::msgcat::mcset $loc Winner

# Statusbar
::msgcat::mcset $loc "Record %s."
::msgcat::mcset $loc "No record available."

# Search dialog
::msgcat::mcset $loc find-prompt Text

