set loc en

::msgcat::mcset $loc Browse...
::msgcat::mcset $loc Cancel
::msgcat::mcset $loc Close
::msgcat::mcset $loc Find
::msgcat::mcset $loc Find...
::msgcat::mcset $loc "Find Again"
::msgcat::mcset $loc OK
::msgcat::mcset $loc "Set Font"


::msgcat::mcset $loc Human
::msgcat::mcset $loc Half-Elf
::msgcat::mcset $loc Elf
::msgcat::mcset $loc Hobbit
::msgcat::mcset $loc Gnome
::msgcat::mcset $loc Dwarf
::msgcat::mcset $loc Half-Orc
::msgcat::mcset $loc Half-Troll
::msgcat::mcset $loc Amberite
::msgcat::mcset $loc High-Elf
::msgcat::mcset $loc Barbarian
::msgcat::mcset $loc Half-Ogre
::msgcat::mcset $loc Half-Giant
::msgcat::mcset $loc Half-Titan
::msgcat::mcset $loc Cyclops
::msgcat::mcset $loc Yeek
::msgcat::mcset $loc Klackon
::msgcat::mcset $loc Kobold
::msgcat::mcset $loc Nibelung
::msgcat::mcset $loc Dark-Elf
::msgcat::mcset $loc Draconian
::msgcat::mcset $loc Mindflayer
::msgcat::mcset $loc Imp
::msgcat::mcset $loc Golem
::msgcat::mcset $loc Skeleton
::msgcat::mcset $loc Zombie
::msgcat::mcset $loc Vampire
::msgcat::mcset $loc Spectre
::msgcat::mcset $loc Sprite
::msgcat::mcset $loc Beastman


::msgcat::mcset $loc Warrior 
::msgcat::mcset $loc Mage 
::msgcat::mcset $loc Priest 
::msgcat::mcset $loc Rogue 
::msgcat::mcset $loc Ranger 
::msgcat::mcset $loc Paladin 
::msgcat::mcset $loc Warrior-Mage 
::msgcat::mcset $loc Chaos-Warrior 
::msgcat::mcset $loc Monk 
::msgcat::mcset $loc Mindcrafter 
::msgcat::mcset $loc High-Mage 


# Book names
::msgcat::mcset $loc Life
::msgcat::mcset $loc Sorcery
::msgcat::mcset $loc Arcane
::msgcat::mcset $loc Trump
::msgcat::mcset $loc Nature
::msgcat::mcset $loc Chaos
::msgcat::mcset $loc Death

