set loc en

# Window title
::msgcat::mcset $loc Assign

# Assign To menu
::msgcat::mcset $loc "Assign To"

# Assign What menu
::msgcat::mcset $loc "Assign What"
::msgcat::mcset $loc Alternate
::msgcat::mcset $loc Icon
::msgcat::mcset $loc Sound
::msgcat::mcset $loc Sprite

# Sound menu
::msgcat::mcset $loc Sound
::msgcat::mcset $loc Configuration
::msgcat::mcset $loc Directory
::msgcat::mcset $loc "Insert Sound"
::msgcat::mcset $loc "Delete Sound"

# Character menu
::msgcat::mcset $loc "Auto Assign..."

# Feature menu
::msgcat::mcset $loc Background...
::msgcat::mcset $loc Memorize
::msgcat::mcset $loc "Town Light"

# Feature -> Lighting menu
::msgcat::mcset $loc Lighting
::msgcat::mcset $loc Icon
::msgcat::mcset $loc None
::msgcat::mcset $loc Tint

# Page titles
::msgcat::mcset $loc Character
::msgcat::mcset $loc Effects
::msgcat::mcset $loc Features
::msgcat::mcset $loc Monsters
::msgcat::mcset $loc Objects

# Effects
::msgcat::mcset $loc Ball
::msgcat::mcset $loc Bolt
::msgcat::mcset $loc Ammunition

# Statusbar
::msgcat::mcset $loc Feature
::msgcat::mcset $loc Monster
::msgcat::mcset $loc Object
::msgcat::mcset $loc "Not assigned."

# Search dialog
::msgcat::mcset $loc find-prompt Name

