set loc jp

# Window title
::msgcat::mcset $loc Assign アサイン

# Assign To menu
::msgcat::mcset $loc "Assign To" アサイン先

# Assign What menu
::msgcat::mcset $loc "Assign What" アサイン種類
::msgcat::mcset $loc Alternate 変える
::msgcat::mcset $loc Icon アイコン
::msgcat::mcset $loc Sound サウンド
::msgcat::mcset $loc Sprite アニメーション

# Sound menu
::msgcat::mcset $loc Sound サウンド
::msgcat::mcset $loc Configuration
::msgcat::mcset $loc Directory
::msgcat::mcset $loc "Insert Sound" サウンド挿入
::msgcat::mcset $loc "Delete Sound" サウンド削除

# Character menu
::msgcat::mcset $loc "Auto Assign..." 自動アサイン

# Feature menu
::msgcat::mcset $loc Background... 背景
::msgcat::mcset $loc Memorize 記憶
::msgcat::mcset $loc "Town Light" 街の明かり

# Feature -> Lighting menu
::msgcat::mcset $loc Lighting 照明
::msgcat::mcset $loc Icon アイコン
::msgcat::mcset $loc None なし
::msgcat::mcset $loc Tint 色

# Page titles
::msgcat::mcset $loc Character 自分
::msgcat::mcset $loc Effects 効果
::msgcat::mcset $loc Features 地形
::msgcat::mcset $loc Monsters モンスター
::msgcat::mcset $loc Objects アイテム

# Effects
::msgcat::mcset $loc Ball
::msgcat::mcset $loc Bolt
::msgcat::mcset $loc Ammunition

# Statusbar
::msgcat::mcset $loc Feature 地形
::msgcat::mcset $loc Monster モンスター
::msgcat::mcset $loc Object アイテム
::msgcat::mcset $loc "Not assigned." なし

# Search dialog
::msgcat::mcset $loc find-prompt 名前

