set loc ja

# Window title
::msgcat::mcset $loc "%s Hall of Fame" "%s 勇者の殿堂"

# Score menu
::msgcat::mcset $loc Score スコア
::msgcat::mcset $loc "Dump Scores" スコアを保存
::msgcat::mcset $loc "Show Record" 記録を見る

# Sort menu
::msgcat::mcset $loc Sort ソート
::msgcat::mcset $loc Class クラス
::msgcat::mcset $loc Name 名前
::msgcat::mcset $loc Race 種族
::msgcat::mcset $loc Score スコア
::msgcat::mcset $loc Winner 勝利者

# Statusbar
::msgcat::mcset $loc "Record %s." "%s を記録"
::msgcat::mcset $loc "No record available." 記録無し

# Search dialog
::msgcat::mcset $loc find-prompt Text

