set loc en

# Window title
::msgcat::mcset $loc Recall

# Monster name
::msgcat::mcset $loc "The "

# Pet commands
::msgcat::mcset $loc "Dismiss pets"
::msgcat::mcset $loc "Stay close"
::msgcat::mcset $loc "Follow me"
::msgcat::mcset $loc "Seek and destroy"
::msgcat::mcset $loc "Give me space"
::msgcat::mcset $loc "Stay away"
::msgcat::mcset $loc "Allow open doors"
::msgcat::mcset $loc "Disallow open doors"
::msgcat::mcset $loc "Allow pickup items"
::msgcat::mcset $loc "Disallow pickup items"

