subdir = ./lib/edit/

## makefile.zb

files += \
  lib/data/a_info.txt lib/data/e_info.txt lib/data/f_info.txt\
  lib/data/k_info.txt lib/data/misc.txt lib/data/r_info.txt\
  lib/data/v_info.txt lib/data/t_info.txt lib/data/w_info.txt
