set loc en

::msgcat::mcset $loc Weak
::msgcat::mcset $loc Hungry
::msgcat::mcset $loc Full
::msgcat::mcset $loc Gorged

::msgcat::mcset $loc Blind
::msgcat::mcset $loc Confused
::msgcat::mcset $loc Afraid
::msgcat::mcset $loc Poisoned
::msgcat::mcset $loc Paralyzed!

::msgcat::mcset $loc "Rest %d"
::msgcat::mcset $loc "Rest *****"
::msgcat::mcset $loc "Rest &&&&&"
::msgcat::mcset $loc "Rep. %d"
::msgcat::mcset $loc "Repeat %d"
::msgcat::mcset $loc Searching

::msgcat::mcset $loc "Fast (%+d)"
::msgcat::mcset $loc "Slow (%+d)"

::msgcat::mcset $loc Study

::msgcat::mcset $loc "Mortal Wound"
::msgcat::mcset $loc "Deep gash"
::msgcat::mcset $loc "Severe cut"
::msgcat::mcset $loc "Nasty cut"
::msgcat::mcset $loc "Bad cut"
::msgcat::mcset $loc "Light cut"
::msgcat::mcset $loc Graze

::msgcat::mcset $loc "Knocked out"
::msgcat::mcset $loc "Heavy stun"
::msgcat::mcset $loc Stun

::msgcat::mcset $loc Wizard
::msgcat::mcset $loc Winner

#
# Extra status messages
#
::msgcat::mcset $loc Blessed
::msgcat::mcset $loc Hero
::msgcat::mcset $loc Berserk
::msgcat::mcset $loc "Res Acid"
::msgcat::mcset $loc "Res Cold"
::msgcat::mcset $loc "Res Elec"
::msgcat::mcset $loc "Res Fire"
::msgcat::mcset $loc "Res Poison"
::msgcat::mcset $loc "Prot Evil"
::msgcat::mcset $loc Shield
::msgcat::mcset $loc Invulnerable

::msgcat::mcset $loc Faster
::msgcat::mcset $loc Slower
::msgcat::mcset $loc Infravision
::msgcat::mcset $loc "See Invis"
::msgcat::mcset $loc Recall
::msgcat::mcset $loc Hallucinate

::msgcat::mcset $loc ESP
::msgcat::mcset $loc Wraith

